///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CityModelDataCity {
/*
{
  "id": 3,
  "user_id": 1,
  "country_id": 2,
  "state_id": 1,
  "name": "Mumbai",
  "status": true,
  "created_at": "2021-10-04T12:01:04.000000Z",
  "updated_at": "2021-10-14T07:04:30.000000Z",
  "deleted_at": null
} 
*/

  int? id;
  int? userId;
  int? countryId;
  int? stateId;
  String? name;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  CityModelDataCity({
    this.id,
    this.userId,
    this.countryId,
    this.stateId,
    this.name,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  CityModelDataCity.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    userId = json["user_id"]?.toInt();
    countryId = json["country_id"]?.toInt();
    stateId = json["state_id"]?.toInt();
    name = json["name"]?.toString();
    status = json["status"];
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    deletedAt = json["deleted_at"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["user_id"] = userId;
    data["country_id"] = countryId;
    data["state_id"] = stateId;
    data["name"] = name;
    data["status"] = status;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["deleted_at"] = deletedAt;
    return data;
  }
}

class CityModelData {
/*
{
  "city": [
    {
      "id": 3,
      "user_id": 1,
      "country_id": 2,
      "state_id": 1,
      "name": "Mumbai",
      "status": true,
      "created_at": "2021-10-04T12:01:04.000000Z",
      "updated_at": "2021-10-14T07:04:30.000000Z",
      "deleted_at": null
    }
  ]
} 
*/

  List<CityModelDataCity?>? city;

  CityModelData({
    this.city,
  });
  CityModelData.fromJson(Map<String, dynamic> json) {
  if (json["city"] != null) {
  final v = json["city"];
  final arr0 = <CityModelDataCity>[];
  v.forEach((v) {
  arr0.add(CityModelDataCity.fromJson(v));
  });
    city = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (city != null) {
      final v = city;
      final arr0 = [];
  v!.forEach((v) {
  arr0.add(v!.toJson());
  });
      data["city"] = arr0;
    }
    return data;
  }
}

class CityModel {
/*
{
  "success": true,
  "data": {
    "city": [
      {
        "id": 3,
        "user_id": 1,
        "country_id": 2,
        "state_id": 1,
        "name": "Mumbai",
        "status": true,
        "created_at": "2021-10-04T12:01:04.000000Z",
        "updated_at": "2021-10-14T07:04:30.000000Z",
        "deleted_at": null
      }
    ]
  },
  "message": "city list."
} 
*/

  bool? success;
  CityModelData? data;
  String? message;

  CityModel({
    this.success,
    this.data,
    this.message,
  });
  CityModel.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    data = (json["data"] != null) ? CityModelData.fromJson(json["data"]) : null;
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["message"] = message;
    return data;
  }
}
