///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GroupDetailsResponseDataGroupUser {
/*
{
  "id": 6,
  "name": "Grishma",
  "email": "Grishma@gmail.com",
  "mobile_number": "7620672068",
  "image": "user/profile/image/B612_20190118_142224_000.jpg"
}
*/

  int? id;
  String? name;
  String? email;
  String? mobileNumber;
  String? image;

  GroupDetailsResponseDataGroupUser({
    this.id,
    this.name,
    this.email,
    this.mobileNumber,
    this.image,
  });
  GroupDetailsResponseDataGroupUser.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    name = json["name"]?.toString();
    email = json["email"]?.toString();
    mobileNumber = json["mobile_number"]?.toString();
    image = json["image"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["name"] = name;
    data["email"] = email;
    data["mobile_number"] = mobileNumber;
    data["image"] = image;
    return data;
  }
}

class GroupDetailsResponseDataGroup {
/*
{
  "id": 13,
  "createted_by": 6,
  "share_id": 3,
  "name": "Group create by Grishma",
  "url": "group/logo/IMG_20210620_174756691.jpg",
  "status": true,
  "created_at": "2021-09-24T09:00:43.000000Z",
  "updated_at": "2021-09-24T09:00:43.000000Z",
  "deleted_at": null,
  "group_join": null,
  "user": {
    "id": 6,
    "name": "Grishma",
    "email": "Grishma@gmail.com",
    "mobile_number": "7620672068",
    "image": "user/profile/image/B612_20190118_142224_000.jpg"
  }
}
*/

  int? id;
  int? createtedBy;
  int? shareId;
  String? name;
  String? url;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;
  String? groupJoin;
  GroupDetailsResponseDataGroupUser? user;

  GroupDetailsResponseDataGroup({
    this.id,
    this.createtedBy,
    this.shareId,
    this.name,
    this.url,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
    this.groupJoin,
    this.user,
  });
  GroupDetailsResponseDataGroup.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    createtedBy = json["createted_by"]?.toInt();
    shareId = json["share_id"]?.toInt();
    name = json["name"]?.toString();
    url = json["url"]?.toString();
    status = json["status"];
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    deletedAt = json["deleted_at"]?.toString();
    groupJoin = json["group_join"]?.toString();
    user = (json["user"] != null) ? GroupDetailsResponseDataGroupUser.fromJson(json["user"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["createted_by"] = createtedBy;
    data["share_id"] = shareId;
    data["name"] = name;
    data["url"] = url;
    data["status"] = status;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["deleted_at"] = deletedAt;
    data["group_join"] = groupJoin;
    if (user != null) {
      data["user"] = user!.toJson();
    }
    return data;
  }
}

class GroupDetailsResponseData {
/*
{
  "group": {
    "id": 13,
    "createted_by": 6,
    "share_id": 3,
    "name": "Group create by Grishma",
    "url": "group/logo/IMG_20210620_174756691.jpg",
    "status": true,
    "created_at": "2021-09-24T09:00:43.000000Z",
    "updated_at": "2021-09-24T09:00:43.000000Z",
    "deleted_at": null,
    "group_join": null,
    "user": {
      "id": 6,
      "name": "Grishma",
      "email": "Grishma@gmail.com",
      "mobile_number": "7620672068",
      "image": "user/profile/image/B612_20190118_142224_000.jpg"
    }
  }
}
*/

  GroupDetailsResponseDataGroup? group;

  GroupDetailsResponseData({
    this.group,
  });
  GroupDetailsResponseData.fromJson(Map<String, dynamic> json) {
    group = (json["group"] != null) ? GroupDetailsResponseDataGroup.fromJson(json["group"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (group != null) {
      data["group"] = group!.toJson();
    }
    return data;
  }
}

class GroupDetailsResponse {
/*
{
  "success": true,
  "data": {
    "group": {
      "id": 13,
      "createted_by": 6,
      "share_id": 3,
      "name": "Group create by Grishma",
      "url": "group/logo/IMG_20210620_174756691.jpg",
      "status": true,
      "created_at": "2021-09-24T09:00:43.000000Z",
      "updated_at": "2021-09-24T09:00:43.000000Z",
      "deleted_at": null,
      "group_join": null,
      "user": {
        "id": 6,
        "name": "Grishma",
        "email": "Grishma@gmail.com",
        "mobile_number": "7620672068",
        "image": "user/profile/image/B612_20190118_142224_000.jpg"
      }
    }
  },
  "message": "Group   list."
}
*/

  bool? success;
  GroupDetailsResponseData? data;
  String? message;

  GroupDetailsResponse({
    this.success,
    this.data,
    this.message,
  });
  GroupDetailsResponse.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    data = (json["data"] != null) ? GroupDetailsResponseData.fromJson(json["data"]) : null;
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["message"] = message;
    return data;
  }
}
