///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GroupJoinedListResponseDataGroupLinks {
/*
{
  "url": null,
  "label": "&laquo; Previous",
  "active": false
}
*/

  String? url;
  String? label;
  bool? active;

  GroupJoinedListResponseDataGroupLinks({
    this.url,
    this.label,
    this.active,
  });
  GroupJoinedListResponseDataGroupLinks.fromJson(Map<String, dynamic> json) {
    url = json["url"]?.toString();
    label = json["label"]?.toString();
    active = json["active"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["url"] = url;
    data["label"] = label;
    data["active"] = active;
    return data;
  }
}

class GroupJoinedListResponseDataGroupDataGroup {
/*
{
  "id": 13,
  "createted_by": 6,
  "share_id": 3,
  "name": "Group create by Grishma",
  "url": "group/logo/IMG_20210620_174756691.jpg",
  "status": true,
  "created_at": "2021-09-24T09:00:43.000000Z",
  "updated_at": "2021-09-24T09:00:43.000000Z",
  "deleted_at": null
}
*/

  int? id;
  int? createtedBy;
  int? shareId;
  String? name;
  String? url;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  GroupJoinedListResponseDataGroupDataGroup({
    this.id,
    this.createtedBy,
    this.shareId,
    this.name,
    this.url,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  GroupJoinedListResponseDataGroupDataGroup.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    createtedBy = json["createted_by"]?.toInt();
    shareId = json["share_id"]?.toInt();
    name = json["name"]?.toString();
    url = json["url"]?.toString();
    status = json["status"];
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    deletedAt = json["deleted_at"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["createted_by"] = createtedBy;
    data["share_id"] = shareId;
    data["name"] = name;
    data["url"] = url;
    data["status"] = status;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["deleted_at"] = deletedAt;
    return data;
  }
}

class GroupJoinedListResponseDataGroupData {
/*
{
  "id": 13,
  "user_id": 6,
  "group_id": 13,
  "status": true,
  "created_at": "2021-09-24T09:25:31.000000Z",
  "updated_at": "2021-09-24T09:25:31.000000Z",
  "deleted_at": null,
  "group": {
    "id": 13,
    "createted_by": 6,
    "share_id": 3,
    "name": "Group create by Grishma",
    "url": "group/logo/IMG_20210620_174756691.jpg",
    "status": true,
    "created_at": "2021-09-24T09:00:43.000000Z",
    "updated_at": "2021-09-24T09:00:43.000000Z",
    "deleted_at": null
  }
}
*/

  int? id;
  int? userId;
  int? groupId;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;
  GroupJoinedListResponseDataGroupDataGroup? group;

  GroupJoinedListResponseDataGroupData({
    this.id,
    this.userId,
    this.groupId,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
    this.group,
  });
  GroupJoinedListResponseDataGroupData.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    userId = json["user_id"]?.toInt();
    groupId = json["group_id"]?.toInt();
    status = json["status"];
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    deletedAt = json["deleted_at"]?.toString();
    group = (json["group"] != null) ? GroupJoinedListResponseDataGroupDataGroup.fromJson(json["group"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["user_id"] = userId;
    data["group_id"] = groupId;
    data["status"] = status;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["deleted_at"] = deletedAt;
    if (group != null) {
      data["group"] = group!.toJson();
    }
    return data;
  }
}

class GroupJoinedListResponseDataGroup {
/*
{
  "current_page": 1,
  "data": [
    {
      "id": 13,
      "user_id": 6,
      "group_id": 13,
      "status": true,
      "created_at": "2021-09-24T09:25:31.000000Z",
      "updated_at": "2021-09-24T09:25:31.000000Z",
      "deleted_at": null,
      "group": {
        "id": 13,
        "createted_by": 6,
        "share_id": 3,
        "name": "Group create by Grishma",
        "url": "group/logo/IMG_20210620_174756691.jpg",
        "status": true,
        "created_at": "2021-09-24T09:00:43.000000Z",
        "updated_at": "2021-09-24T09:00:43.000000Z",
        "deleted_at": null
      }
    }
  ],
  "first_page_url": "http://192.168.10.8/prof_vanam/public/api/join-group?page=1",
  "from": 1,
  "last_page": 1,
  "last_page_url": "http://192.168.10.8/prof_vanam/public/api/join-group?page=1",
  "links": [
    {
      "url": null,
      "label": "&laquo; Previous",
      "active": false
    }
  ],
  "next_page_url": null,
  "path": "http://192.168.10.8/prof_vanam/public/api/join-group",
  "per_page": 10,
  "prev_page_url": null,
  "to": 1,
  "total": 1
}
*/

  int? currentPage;
  List<GroupJoinedListResponseDataGroupData?>? data;
  String? firstPageUrl;
  int? from;
  int? lastPage;
  String? lastPageUrl;
  List<GroupJoinedListResponseDataGroupLinks?>? links;
  String? nextPageUrl;
  String? path;
  int? perPage;
  String? prevPageUrl;
  int? to;
  int? total;

  GroupJoinedListResponseDataGroup({
    this.currentPage,
    this.data,
    this.firstPageUrl,
    this.from,
    this.lastPage,
    this.lastPageUrl,
    this.links,
    this.nextPageUrl,
    this.path,
    this.perPage,
    this.prevPageUrl,
    this.to,
    this.total,
  });
  GroupJoinedListResponseDataGroup.fromJson(Map<String, dynamic> json) {
    currentPage = json["current_page"]?.toInt();
    if (json["data"] != null) {
      final v = json["data"];
      final arr0 = <GroupJoinedListResponseDataGroupData>[];
      v.forEach((v) {
        arr0.add(GroupJoinedListResponseDataGroupData.fromJson(v));
      });
      this.data = arr0;
    }
    firstPageUrl = json["first_page_url"]?.toString();
    from = json["from"]?.toInt();
    lastPage = json["last_page"]?.toInt();
    lastPageUrl = json["last_page_url"]?.toString();
    if (json["links"] != null) {
      final v = json["links"];
      final arr0 = <GroupJoinedListResponseDataGroupLinks>[];
      v.forEach((v) {
        arr0.add(GroupJoinedListResponseDataGroupLinks.fromJson(v));
      });
      links = arr0;
    }
    nextPageUrl = json["next_page_url"]?.toString();
    path = json["path"]?.toString();
    perPage = json["per_page"]?.toInt();
    prevPageUrl = json["prev_page_url"]?.toString();
    to = json["to"]?.toInt();
    total = json["total"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["current_page"] = currentPage;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["data"] = arr0;
    }
    data["first_page_url"] = firstPageUrl;
    data["from"] = from;
    data["last_page"] = lastPage;
    data["last_page_url"] = lastPageUrl;
    if (links != null) {
      final v = links;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["links"] = arr0;
    }
    data["next_page_url"] = nextPageUrl;
    data["path"] = path;
    data["per_page"] = perPage;
    data["prev_page_url"] = prevPageUrl;
    data["to"] = to;
    data["total"] = total;
    return data;
  }
}

class GroupJoinedListResponseData {
/*
{
  "group": {
    "current_page": 1,
    "data": [
      {
        "id": 13,
        "user_id": 6,
        "group_id": 13,
        "status": true,
        "created_at": "2021-09-24T09:25:31.000000Z",
        "updated_at": "2021-09-24T09:25:31.000000Z",
        "deleted_at": null,
        "group": {
          "id": 13,
          "createted_by": 6,
          "share_id": 3,
          "name": "Group create by Grishma",
          "url": "group/logo/IMG_20210620_174756691.jpg",
          "status": true,
          "created_at": "2021-09-24T09:00:43.000000Z",
          "updated_at": "2021-09-24T09:00:43.000000Z",
          "deleted_at": null
        }
      }
    ],
    "first_page_url": "http://192.168.10.8/prof_vanam/public/api/join-group?page=1",
    "from": 1,
    "last_page": 1,
    "last_page_url": "http://192.168.10.8/prof_vanam/public/api/join-group?page=1",
    "links": [
      {
        "url": null,
        "label": "&laquo; Previous",
        "active": false
      }
    ],
    "next_page_url": null,
    "path": "http://192.168.10.8/prof_vanam/public/api/join-group",
    "per_page": 10,
    "prev_page_url": null,
    "to": 1,
    "total": 1
  }
}
*/

  GroupJoinedListResponseDataGroup? group;

  GroupJoinedListResponseData({
    this.group,
  });
  GroupJoinedListResponseData.fromJson(Map<String, dynamic> json) {
    group = (json["group"] != null) ? GroupJoinedListResponseDataGroup.fromJson(json["group"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (group != null) {
      data["group"] = group!.toJson();
    }
    return data;
  }
}

class GroupJoinedListResponse {
/*
{
  "success": true,
  "data": {
    "group": {
      "current_page": 1,
      "data": [
        {
          "id": 13,
          "user_id": 6,
          "group_id": 13,
          "status": true,
          "created_at": "2021-09-24T09:25:31.000000Z",
          "updated_at": "2021-09-24T09:25:31.000000Z",
          "deleted_at": null,
          "group": {
            "id": 13,
            "createted_by": 6,
            "share_id": 3,
            "name": "Group create by Grishma",
            "url": "group/logo/IMG_20210620_174756691.jpg",
            "status": true,
            "created_at": "2021-09-24T09:00:43.000000Z",
            "updated_at": "2021-09-24T09:00:43.000000Z",
            "deleted_at": null
          }
        }
      ],
      "first_page_url": "http://192.168.10.8/prof_vanam/public/api/join-group?page=1",
      "from": 1,
      "last_page": 1,
      "last_page_url": "http://192.168.10.8/prof_vanam/public/api/join-group?page=1",
      "links": [
        {
          "url": null,
          "label": "&laquo; Previous",
          "active": false
        }
      ],
      "next_page_url": null,
      "path": "http://192.168.10.8/prof_vanam/public/api/join-group",
      "per_page": 10,
      "prev_page_url": null,
      "to": 1,
      "total": 1
    }
  },
  "message": "Group   list."
}
*/

  bool? success;
  GroupJoinedListResponseData? data;
  String? message;

  GroupJoinedListResponse({
    this.success,
    this.data,
    this.message,
  });
  GroupJoinedListResponse.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    data = (json["data"] != null) ? GroupJoinedListResponseData.fromJson(json["data"]) : null;
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["message"] = message;
    return data;
  }
}
