///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GroupJoinResponseData {
/*
{
  "group-join": "group join successfully"
}
*/

  String? groupJoin;

  GroupJoinResponseData({
    this.groupJoin,
  });
  GroupJoinResponseData.fromJson(Map<String, dynamic> json) {
    groupJoin = json["group-join"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["group-join"] = groupJoin;
    return data;
  }
}

class GroupJoinResponse {
/*
{
  "success": true,
  "data": {
    "group-join": "group join successfully"
  },
  "message": "group join successfully."
}
*/

  bool? success;
  GroupJoinResponseData? data;
  String? message;

  GroupJoinResponse({
    this.success,
    this.data,
    this.message,
  });
  GroupJoinResponse.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    data = (json["data"] != null) ? GroupJoinResponseData.fromJson(json["data"]) : null;
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["message"] = message;
    return data;
  }
}
