///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GroupMemberListResponseDataGroupMemberLinks {
/*
{
  "url": null,
  "label": "&laquo; Previous",
  "active": false
}
*/

  String? url;
  String? label;
  bool? active;

  GroupMemberListResponseDataGroupMemberLinks({
    this.url,
    this.label,
    this.active,
  });
  GroupMemberListResponseDataGroupMemberLinks.fromJson(Map<String, dynamic> json) {
    url = json["url"]?.toString();
    label = json["label"]?.toString();
    active = json["active"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["url"] = url;
    data["label"] = label;
    data["active"] = active;
    return data;
  }
}

class GroupMemberListResponseDataGroupMemberDataUser {
/*
{
  "id": 22,
  "name": "jayesh",
  "email": "shinde@gmail.com",
  "mobile_number": "7304610113",
  "image": "user/profile/image/IMG_20210916_111325.jpg"
}
*/

  int? id;
  String? name;
  String? email;
  String? mobileNumber;
  String? image;

  GroupMemberListResponseDataGroupMemberDataUser({
    this.id,
    this.name,
    this.email,
    this.mobileNumber,
    this.image,
  });
  GroupMemberListResponseDataGroupMemberDataUser.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    name = json["name"]?.toString();
    email = json["email"]?.toString();
    mobileNumber = json["mobile_number"]?.toString();
    image = json["image"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["name"] = name;
    data["email"] = email;
    data["mobile_number"] = mobileNumber;
    data["image"] = image;
    return data;
  }
}

class GroupMemberListResponseDataGroupMemberData {
/*
{
  "id": 1,
  "user_id": 22,
  "group_id": 1,
  "status": false,
  "created_at": "2021-09-18T09:57:04.000000Z",
  "updated_at": "2021-09-18T10:05:57.000000Z",
  "deleted_at": null,
  "user": {
    "id": 22,
    "name": "jayesh",
    "email": "shinde@gmail.com",
    "mobile_number": "7304610113",
    "image": "user/profile/image/IMG_20210916_111325.jpg"
  }
}
*/

  int? id;
  int? userId;
  int? groupId;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;
  GroupMemberListResponseDataGroupMemberDataUser? user;

  GroupMemberListResponseDataGroupMemberData({
    this.id,
    this.userId,
    this.groupId,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
    this.user,
  });
  GroupMemberListResponseDataGroupMemberData.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    userId = json["user_id"]?.toInt();
    groupId = json["group_id"]?.toInt();
    status = json["status"];
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    deletedAt = json["deleted_at"]?.toString();
    user = (json["user"] != null) ? GroupMemberListResponseDataGroupMemberDataUser.fromJson(json["user"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["user_id"] = userId;
    data["group_id"] = groupId;
    data["status"] = status;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["deleted_at"] = deletedAt;
    if (user != null) {
      data["user"] = user!.toJson();
    }
    return data;
  }
}

class GroupMemberListResponseDataGroupMember {
/*
{
  "current_page": 1,
  "data": [
    {
      "id": 1,
      "user_id": 22,
      "group_id": 1,
      "status": false,
      "created_at": "2021-09-18T09:57:04.000000Z",
      "updated_at": "2021-09-18T10:05:57.000000Z",
      "deleted_at": null,
      "user": {
        "id": 22,
        "name": "jayesh",
        "email": "shinde@gmail.com",
        "mobile_number": "7304610113",
        "image": "user/profile/image/IMG_20210916_111325.jpg"
      }
    }
  ],
  "first_page_url": "http://192.168.10.8/prof_vanam/public/api/group-join?page=1",
  "from": 1,
  "last_page": 1,
  "last_page_url": "http://192.168.10.8/prof_vanam/public/api/group-join?page=1",
  "links": [
    {
      "url": null,
      "label": "&laquo; Previous",
      "active": false
    }
  ],
  "next_page_url": null,
  "path": "http://192.168.10.8/prof_vanam/public/api/group-join",
  "per_page": 10,
  "prev_page_url": null,
  "to": 2,
  "total": 2
}
*/

  int? currentPage;
  List<GroupMemberListResponseDataGroupMemberData?>? data;
  String? firstPageUrl;
  int? from;
  int? lastPage;
  String? lastPageUrl;
  List<GroupMemberListResponseDataGroupMemberLinks?>? links;
  String? nextPageUrl;
  String? path;
  int? perPage;
  String? prevPageUrl;
  int? to;
  int? total;

  GroupMemberListResponseDataGroupMember({
    this.currentPage,
    this.data,
    this.firstPageUrl,
    this.from,
    this.lastPage,
    this.lastPageUrl,
    this.links,
    this.nextPageUrl,
    this.path,
    this.perPage,
    this.prevPageUrl,
    this.to,
    this.total,
  });
  GroupMemberListResponseDataGroupMember.fromJson(Map<String, dynamic> json) {
    currentPage = json["current_page"]?.toInt();
    if (json["data"] != null) {
      final v = json["data"];
      final arr0 = <GroupMemberListResponseDataGroupMemberData>[];
      v.forEach((v) {
        arr0.add(GroupMemberListResponseDataGroupMemberData.fromJson(v));
      });
      this.data = arr0;
    }
    firstPageUrl = json["first_page_url"]?.toString();
    from = json["from"]?.toInt();
    lastPage = json["last_page"]?.toInt();
    lastPageUrl = json["last_page_url"]?.toString();
    if (json["links"] != null) {
      final v = json["links"];
      final arr0 = <GroupMemberListResponseDataGroupMemberLinks>[];
      v.forEach((v) {
        arr0.add(GroupMemberListResponseDataGroupMemberLinks.fromJson(v));
      });
      links = arr0;
    }
    nextPageUrl = json["next_page_url"]?.toString();
    path = json["path"]?.toString();
    perPage = json["per_page"]?.toInt();
    prevPageUrl = json["prev_page_url"]?.toString();
    to = json["to"]?.toInt();
    total = json["total"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["current_page"] = currentPage;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["data"] = arr0;
    }
    data["first_page_url"] = firstPageUrl;
    data["from"] = from;
    data["last_page"] = lastPage;
    data["last_page_url"] = lastPageUrl;
    if (links != null) {
      final v = links;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["links"] = arr0;
    }
    data["next_page_url"] = nextPageUrl;
    data["path"] = path;
    data["per_page"] = perPage;
    data["prev_page_url"] = prevPageUrl;
    data["to"] = to;
    data["total"] = total;
    return data;
  }
}

class GroupMemberListResponseData {
/*
{
  "group-member": {
    "current_page": 1,
    "data": [
      {
        "id": 1,
        "user_id": 22,
        "group_id": 1,
        "status": false,
        "created_at": "2021-09-18T09:57:04.000000Z",
        "updated_at": "2021-09-18T10:05:57.000000Z",
        "deleted_at": null,
        "user": {
          "id": 22,
          "name": "jayesh",
          "email": "shinde@gmail.com",
          "mobile_number": "7304610113",
          "image": "user/profile/image/IMG_20210916_111325.jpg"
        }
      }
    ],
    "first_page_url": "http://192.168.10.8/prof_vanam/public/api/group-join?page=1",
    "from": 1,
    "last_page": 1,
    "last_page_url": "http://192.168.10.8/prof_vanam/public/api/group-join?page=1",
    "links": [
      {
        "url": null,
        "label": "&laquo; Previous",
        "active": false
      }
    ],
    "next_page_url": null,
    "path": "http://192.168.10.8/prof_vanam/public/api/group-join",
    "per_page": 10,
    "prev_page_url": null,
    "to": 2,
    "total": 2
  }
}
*/

  GroupMemberListResponseDataGroupMember? groupMember;

  GroupMemberListResponseData({
    this.groupMember,
  });
  GroupMemberListResponseData.fromJson(Map<String, dynamic> json) {
    groupMember = (json["group-member"] != null) ? GroupMemberListResponseDataGroupMember.fromJson(json["group-member"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (groupMember != null) {
      data["group-member"] = groupMember!.toJson();
    }
    return data;
  }
}

class GroupMemberListResponse {
/*
{
  "success": true,
  "data": {
    "group-member": {
      "current_page": 1,
      "data": [
        {
          "id": 1,
          "user_id": 22,
          "group_id": 1,
          "status": false,
          "created_at": "2021-09-18T09:57:04.000000Z",
          "updated_at": "2021-09-18T10:05:57.000000Z",
          "deleted_at": null,
          "user": {
            "id": 22,
            "name": "jayesh",
            "email": "shinde@gmail.com",
            "mobile_number": "7304610113",
            "image": "user/profile/image/IMG_20210916_111325.jpg"
          }
        }
      ],
      "first_page_url": "http://192.168.10.8/prof_vanam/public/api/group-join?page=1",
      "from": 1,
      "last_page": 1,
      "last_page_url": "http://192.168.10.8/prof_vanam/public/api/group-join?page=1",
      "links": [
        {
          "url": null,
          "label": "&laquo; Previous",
          "active": false
        }
      ],
      "next_page_url": null,
      "path": "http://192.168.10.8/prof_vanam/public/api/group-join",
      "per_page": 10,
      "prev_page_url": null,
      "to": 2,
      "total": 2
    }
  },
  "message": "Group   list."
}
*/

  bool? success;
  GroupMemberListResponseData? data;
  String? message;

  GroupMemberListResponse({
    this.success,
    this.data,
    this.message,
  });
  GroupMemberListResponse.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    data = (json["data"] != null) ? GroupMemberListResponseData.fromJson(json["data"]) : null;
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["message"] = message;
    return data;
  }
}
