///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GroupInviteListResponseDataGroupInviteLinks {
/*
{
  "url": null,
  "label": "&laquo; Previous",
  "active": false
}
*/

  String? url;
  String? label;
  bool? active;

  GroupInviteListResponseDataGroupInviteLinks({
    this.url,
    this.label,
    this.active,
  });
  GroupInviteListResponseDataGroupInviteLinks.fromJson(Map<String, dynamic> json) {
    url = json["url"]?.toString();
    label = json["label"]?.toString();
    active = json["active"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["url"] = url;
    data["label"] = label;
    data["active"] = active;
    return data;
  }
}

class GroupInviteListResponseDataGroupInviteDataGroupInvite {
/*
{
  "id": 2,
  "invited_by": 22,
  "user_id": 1,
  "group_id": 5,
  "status": true,
  "created_at": "2021-09-18T12:37:20.000000Z",
  "updated_at": "2021-09-18T12:37:20.000000Z",
  "deleted_at": null
}
*/

  int? id;
  int? invitedBy;
  int? userId;
  int? groupId;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  GroupInviteListResponseDataGroupInviteDataGroupInvite({
    this.id,
    this.invitedBy,
    this.userId,
    this.groupId,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  GroupInviteListResponseDataGroupInviteDataGroupInvite.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    invitedBy = json["invited_by"]?.toInt();
    userId = json["user_id"]?.toInt();
    groupId = json["group_id"]?.toInt();
    status = json["status"];
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    deletedAt = json["deleted_at"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["invited_by"] = invitedBy;
    data["user_id"] = userId;
    data["group_id"] = groupId;
    data["status"] = status;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["deleted_at"] = deletedAt;
    return data;
  }
}

class GroupInviteListResponseDataGroupInviteData {
/*
{
  "id": 1,
  "name": "jayesh",
  "image": null,
  "group_invite": {
    "id": 2,
    "invited_by": 22,
    "user_id": 1,
    "group_id": 5,
    "status": true,
    "created_at": "2021-09-18T12:37:20.000000Z",
    "updated_at": "2021-09-18T12:37:20.000000Z",
    "deleted_at": null
  }
}
*/

  int? id;
  String? name;
  String? image;
  GroupInviteListResponseDataGroupInviteDataGroupInvite? groupInvite;

  GroupInviteListResponseDataGroupInviteData({
    this.id,
    this.name,
    this.image,
    this.groupInvite,
  });
  GroupInviteListResponseDataGroupInviteData.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    name = json["name"]?.toString();
    image = json["image"]?.toString();
    groupInvite = (json["group_invite"] != null) ? GroupInviteListResponseDataGroupInviteDataGroupInvite.fromJson(json["group_invite"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["name"] = name;
    data["image"] = image;
    if (groupInvite != null) {
      data["group_invite"] = groupInvite!.toJson();
    }
    return data;
  }
}

class GroupInviteListResponseDataGroupInvite {
/*
{
  "current_page": 1,
  "data": [
    {
      "id": 1,
      "name": "jayesh",
      "image": null,
      "group_invite": {
        "id": 2,
        "invited_by": 22,
        "user_id": 1,
        "group_id": 5,
        "status": true,
        "created_at": "2021-09-18T12:37:20.000000Z",
        "updated_at": "2021-09-18T12:37:20.000000Z",
        "deleted_at": null
      }
    }
  ],
  "first_page_url": "http://192.168.10.8/prof_vanam/public/api/group-invite?page=1",
  "from": 1,
  "last_page": 3,
  "last_page_url": "http://192.168.10.8/prof_vanam/public/api/group-invite?page=3",
  "links": [
    {
      "url": null,
      "label": "&laquo; Previous",
      "active": false
    }
  ],
  "next_page_url": "http://192.168.10.8/prof_vanam/public/api/group-invite?page=2",
  "path": "http://192.168.10.8/prof_vanam/public/api/group-invite",
  "per_page": 10,
  "prev_page_url": null,
  "to": 10,
  "total": 25
}
*/

  int? currentPage;
  List<GroupInviteListResponseDataGroupInviteData?>? data;
  String? firstPageUrl;
  int? from;
  int? lastPage;
  String? lastPageUrl;
  List<GroupInviteListResponseDataGroupInviteLinks?>? links;
  String? nextPageUrl;
  String? path;
  int? perPage;
  String? prevPageUrl;
  int? to;
  int? total;

  GroupInviteListResponseDataGroupInvite({
    this.currentPage,
    this.data,
    this.firstPageUrl,
    this.from,
    this.lastPage,
    this.lastPageUrl,
    this.links,
    this.nextPageUrl,
    this.path,
    this.perPage,
    this.prevPageUrl,
    this.to,
    this.total,
  });
  GroupInviteListResponseDataGroupInvite.fromJson(Map<String, dynamic> json) {
    currentPage = json["current_page"]?.toInt();
    if (json["data"] != null) {
      final v = json["data"];
      final arr0 = <GroupInviteListResponseDataGroupInviteData>[];
      v.forEach((v) {
        arr0.add(GroupInviteListResponseDataGroupInviteData.fromJson(v));
      });
      this.data = arr0;
    }
    firstPageUrl = json["first_page_url"]?.toString();
    from = json["from"]?.toInt();
    lastPage = json["last_page"]?.toInt();
    lastPageUrl = json["last_page_url"]?.toString();
    if (json["links"] != null) {
      final v = json["links"];
      final arr0 = <GroupInviteListResponseDataGroupInviteLinks>[];
      v.forEach((v) {
        arr0.add(GroupInviteListResponseDataGroupInviteLinks.fromJson(v));
      });
      links = arr0;
    }
    nextPageUrl = json["next_page_url"]?.toString();
    path = json["path"]?.toString();
    perPage = json["per_page"]?.toInt();
    prevPageUrl = json["prev_page_url"]?.toString();
    to = json["to"]?.toInt();
    total = json["total"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["current_page"] = currentPage;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["data"] = arr0;
    }
    data["first_page_url"] = firstPageUrl;
    data["from"] = from;
    data["last_page"] = lastPage;
    data["last_page_url"] = lastPageUrl;
    if (links != null) {
      final v = links;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["links"] = arr0;
    }
    data["next_page_url"] = nextPageUrl;
    data["path"] = path;
    data["per_page"] = perPage;
    data["prev_page_url"] = prevPageUrl;
    data["to"] = to;
    data["total"] = total;
    return data;
  }
}

class GroupInviteListResponseData {
/*
{
  "group-invite": {
    "current_page": 1,
    "data": [
      {
        "id": 1,
        "name": "jayesh",
        "image": null,
        "group_invite": {
          "id": 2,
          "invited_by": 22,
          "user_id": 1,
          "group_id": 5,
          "status": true,
          "created_at": "2021-09-18T12:37:20.000000Z",
          "updated_at": "2021-09-18T12:37:20.000000Z",
          "deleted_at": null
        }
      }
    ],
    "first_page_url": "http://192.168.10.8/prof_vanam/public/api/group-invite?page=1",
    "from": 1,
    "last_page": 3,
    "last_page_url": "http://192.168.10.8/prof_vanam/public/api/group-invite?page=3",
    "links": [
      {
        "url": null,
        "label": "&laquo; Previous",
        "active": false
      }
    ],
    "next_page_url": "http://192.168.10.8/prof_vanam/public/api/group-invite?page=2",
    "path": "http://192.168.10.8/prof_vanam/public/api/group-invite",
    "per_page": 10,
    "prev_page_url": null,
    "to": 10,
    "total": 25
  }
}
*/

  GroupInviteListResponseDataGroupInvite? groupInvite;

  GroupInviteListResponseData({
    this.groupInvite,
  });
  GroupInviteListResponseData.fromJson(Map<String, dynamic> json) {
    groupInvite = (json["group-invite"] != null) ? GroupInviteListResponseDataGroupInvite.fromJson(json["group-invite"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (groupInvite != null) {
      data["group-invite"] = groupInvite!.toJson();
    }
    return data;
  }
}

class GroupInviteListResponse {
/*
{
  "success": true,
  "data": {
    "group-invite": {
      "current_page": 1,
      "data": [
        {
          "id": 1,
          "name": "jayesh",
          "image": null,
          "group_invite": {
            "id": 2,
            "invited_by": 22,
            "user_id": 1,
            "group_id": 5,
            "status": true,
            "created_at": "2021-09-18T12:37:20.000000Z",
            "updated_at": "2021-09-18T12:37:20.000000Z",
            "deleted_at": null
          }
        }
      ],
      "first_page_url": "http://192.168.10.8/prof_vanam/public/api/group-invite?page=1",
      "from": 1,
      "last_page": 3,
      "last_page_url": "http://192.168.10.8/prof_vanam/public/api/group-invite?page=3",
      "links": [
        {
          "url": null,
          "label": "&laquo; Previous",
          "active": false
        }
      ],
      "next_page_url": "http://192.168.10.8/prof_vanam/public/api/group-invite?page=2",
      "path": "http://192.168.10.8/prof_vanam/public/api/group-invite",
      "per_page": 10,
      "prev_page_url": null,
      "to": 10,
      "total": 25
    }
  },
  "message": "Group   list."
}
*/

  bool? success;
  GroupInviteListResponseData? data;
  String? message;

  GroupInviteListResponse({
    this.success,
    this.data,
    this.message,
  });
  GroupInviteListResponse.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    data = (json["data"] != null) ? GroupInviteListResponseData.fromJson(json["data"]) : null;
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["message"] = message;
    return data;
  }
}
