///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class GroupShareWithResponseDataShareWith {
/*
{
  "id": 1,
  "user_id": 1,
  "name": "Public",
  "status": true,
  "created_at": "2021-07-14T07:28:12.000000Z",
  "updated_at": "2021-07-14T07:28:12.000000Z",
  "deleted_at": null
}
*/

  int? id;
  int? userId;
  String? name;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  GroupShareWithResponseDataShareWith({
    this.id,
    this.userId,
    this.name,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  GroupShareWithResponseDataShareWith.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    userId = json["user_id"]?.toInt();
    name = json["name"]?.toString();
    status = json["status"];
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    deletedAt = json["deleted_at"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["user_id"] = userId;
    data["name"] = name;
    data["status"] = status;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["deleted_at"] = deletedAt;
    return data;
  }
}

class GroupShareWithResponseData {
/*
{
  "share_with": [
    {
      "id": 1,
      "user_id": 1,
      "name": "Public",
      "status": true,
      "created_at": "2021-07-14T07:28:12.000000Z",
      "updated_at": "2021-07-14T07:28:12.000000Z",
      "deleted_at": null
    }
  ]
}
*/

  List<GroupShareWithResponseDataShareWith?>? shareWith;

  GroupShareWithResponseData({
    this.shareWith,
  });
  GroupShareWithResponseData.fromJson(Map<String, dynamic> json) {
    if (json["share_with"] != null) {
      final v = json["share_with"];
      final arr0 = <GroupShareWithResponseDataShareWith>[];
      v.forEach((v) {
        arr0.add(GroupShareWithResponseDataShareWith.fromJson(v));
      });
      shareWith = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (shareWith != null) {
      final v = shareWith;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["share_with"] = arr0;
    }
    return data;
  }
}

class GroupShareWithResponse {
/*
{
  "success": true,
  "data": {
    "share_with": [
      {
        "id": 1,
        "user_id": 1,
        "name": "Public",
        "status": true,
        "created_at": "2021-07-14T07:28:12.000000Z",
        "updated_at": "2021-07-14T07:28:12.000000Z",
        "deleted_at": null
      }
    ]
  },
  "message": "Share With list."
}
*/

  bool? success;
  GroupShareWithResponseData? data;
  String? message;

  GroupShareWithResponse({
    this.success,
    this.data,
    this.message,
  });
  GroupShareWithResponse.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    data = (json["data"] != null) ? GroupShareWithResponseData.fromJson(json["data"]) : null;
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["message"] = message;
    return data;
  }
}
