///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PopularGroupResponseDataGroupLinks {
/*
{
  "url": null,
  "label": "&laquo; Previous",
  "active": false
}
*/

  String? url;
  String? label;
  bool? active;

  PopularGroupResponseDataGroupLinks({
    this.url,
    this.label,
    this.active,
  });
  PopularGroupResponseDataGroupLinks.fromJson(Map<String, dynamic> json) {
    url = json["url"]?.toString();
    label = json["label"]?.toString();
    active = json["active"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["url"] = url;
    data["label"] = label;
    data["active"] = active;
    return data;
  }
}

class PopularGroupResponseDataGroupData {
/*
{
  "id": 8,
  "createted_by": 9,
  "share_id": 1,
  "name": "group test 99",
  "url": "group/logo/IMG_20210920_110041.jpg",
  "status": true,
  "created_at": "2021-09-20T05:48:01.000000Z",
  "updated_at": "2021-09-20T05:48:01.000000Z",
  "deleted_at": null
}
*/

  int? id;
  int? createtedBy;
  int? shareId;
  String? name;
  String? url;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  PopularGroupResponseDataGroupData({
    this.id,
    this.createtedBy,
    this.shareId,
    this.name,
    this.url,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  PopularGroupResponseDataGroupData.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    createtedBy = json["createted_by"]?.toInt();
    shareId = json["share_id"]?.toInt();
    name = json["name"]?.toString();
    url = json["url"]?.toString();
    status = json["status"];
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    deletedAt = json["deleted_at"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["createted_by"] = createtedBy;
    data["share_id"] = shareId;
    data["name"] = name;
    data["url"] = url;
    data["status"] = status;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["deleted_at"] = deletedAt;
    return data;
  }
}

class PopularGroupResponseDataGroup {
/*
{
  "current_page": 1,
  "data": [
    {
      "id": 8,
      "createted_by": 9,
      "share_id": 1,
      "name": "group test 99",
      "url": "group/logo/IMG_20210920_110041.jpg",
      "status": true,
      "created_at": "2021-09-20T05:48:01.000000Z",
      "updated_at": "2021-09-20T05:48:01.000000Z",
      "deleted_at": null
    }
  ],
  "first_page_url": "http://192.168.10.8/prof_vanam/public/api/popular-group?page=1",
  "from": 1,
  "last_page": 1,
  "last_page_url": "http://192.168.10.8/prof_vanam/public/api/popular-group?page=1",
  "links": [
    {
      "url": null,
      "label": "&laquo; Previous",
      "active": false
    }
  ],
  "next_page_url": null,
  "path": "http://192.168.10.8/prof_vanam/public/api/popular-group",
  "per_page": 10,
  "prev_page_url": null,
  "to": 2,
  "total": 2
}
*/

  int? currentPage;
  List<PopularGroupResponseDataGroupData?>? data;
  String? firstPageUrl;
  int? from;
  int? lastPage;
  String? lastPageUrl;
  List<PopularGroupResponseDataGroupLinks?>? links;
  String? nextPageUrl;
  String? path;
  int? perPage;
  String? prevPageUrl;
  int? to;
  int? total;

  PopularGroupResponseDataGroup({
    this.currentPage,
    this.data,
    this.firstPageUrl,
    this.from,
    this.lastPage,
    this.lastPageUrl,
    this.links,
    this.nextPageUrl,
    this.path,
    this.perPage,
    this.prevPageUrl,
    this.to,
    this.total,
  });
  PopularGroupResponseDataGroup.fromJson(Map<String, dynamic> json) {
    currentPage = json["current_page"]?.toInt();
    if (json["data"] != null) {
      final v = json["data"];
      final arr0 = <PopularGroupResponseDataGroupData>[];
      v.forEach((v) {
        arr0.add(PopularGroupResponseDataGroupData.fromJson(v));
      });
      this.data = arr0;
    }
    firstPageUrl = json["first_page_url"]?.toString();
    from = json["from"]?.toInt();
    lastPage = json["last_page"]?.toInt();
    lastPageUrl = json["last_page_url"]?.toString();
    if (json["links"] != null) {
      final v = json["links"];
      final arr0 = <PopularGroupResponseDataGroupLinks>[];
      v.forEach((v) {
        arr0.add(PopularGroupResponseDataGroupLinks.fromJson(v));
      });
      links = arr0;
    }
    nextPageUrl = json["next_page_url"]?.toString();
    path = json["path"]?.toString();
    perPage = json["per_page"]?.toInt();
    prevPageUrl = json["prev_page_url"]?.toString();
    to = json["to"]?.toInt();
    total = json["total"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["current_page"] = currentPage;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["data"] = arr0;
    }
    data["first_page_url"] = firstPageUrl;
    data["from"] = from;
    data["last_page"] = lastPage;
    data["last_page_url"] = lastPageUrl;
    if (links != null) {
      final v = links;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["links"] = arr0;
    }
    data["next_page_url"] = nextPageUrl;
    data["path"] = path;
    data["per_page"] = perPage;
    data["prev_page_url"] = prevPageUrl;
    data["to"] = to;
    data["total"] = total;
    return data;
  }
}

class PopularGroupResponseData {
/*
{
  "group": {
    "current_page": 1,
    "data": [
      {
        "id": 8,
        "createted_by": 9,
        "share_id": 1,
        "name": "group test 99",
        "url": "group/logo/IMG_20210920_110041.jpg",
        "status": true,
        "created_at": "2021-09-20T05:48:01.000000Z",
        "updated_at": "2021-09-20T05:48:01.000000Z",
        "deleted_at": null
      }
    ],
    "first_page_url": "http://192.168.10.8/prof_vanam/public/api/popular-group?page=1",
    "from": 1,
    "last_page": 1,
    "last_page_url": "http://192.168.10.8/prof_vanam/public/api/popular-group?page=1",
    "links": [
      {
        "url": null,
        "label": "&laquo; Previous",
        "active": false
      }
    ],
    "next_page_url": null,
    "path": "http://192.168.10.8/prof_vanam/public/api/popular-group",
    "per_page": 10,
    "prev_page_url": null,
    "to": 2,
    "total": 2
  }
}
*/

  PopularGroupResponseDataGroup? group;

  PopularGroupResponseData({
    this.group,
  });
  PopularGroupResponseData.fromJson(Map<String, dynamic> json) {
    group = (json["group"] != null) ? PopularGroupResponseDataGroup.fromJson(json["group"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (group != null) {
      data["group"] = group!.toJson();
    }
    return data;
  }
}

class PopularGroupResponse {
/*
{
  "success": true,
  "data": {
    "group": {
      "current_page": 1,
      "data": [
        {
          "id": 8,
          "createted_by": 9,
          "share_id": 1,
          "name": "group test 99",
          "url": "group/logo/IMG_20210920_110041.jpg",
          "status": true,
          "created_at": "2021-09-20T05:48:01.000000Z",
          "updated_at": "2021-09-20T05:48:01.000000Z",
          "deleted_at": null
        }
      ],
      "first_page_url": "http://192.168.10.8/prof_vanam/public/api/popular-group?page=1",
      "from": 1,
      "last_page": 1,
      "last_page_url": "http://192.168.10.8/prof_vanam/public/api/popular-group?page=1",
      "links": [
        {
          "url": null,
          "label": "&laquo; Previous",
          "active": false
        }
      ],
      "next_page_url": null,
      "path": "http://192.168.10.8/prof_vanam/public/api/popular-group",
      "per_page": 10,
      "prev_page_url": null,
      "to": 2,
      "total": 2
    }
  },
  "message": "Group   list."
}
*/

  bool? success;
  PopularGroupResponseData? data;
  String? message;

  PopularGroupResponse({
    this.success,
    this.data,
    this.message,
  });
  PopularGroupResponse.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    data = (json["data"] != null) ? PopularGroupResponseData.fromJson(json["data"]) : null;
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["message"] = message;
    return data;
  }
}
