///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class FriendBlockListResponseDataUserListLinks {
/*
{
  "url": null,
  "label": "&laquo; Previous",
  "active": false
}
*/

  String? url;
  String? label;
  bool? active;

  FriendBlockListResponseDataUserListLinks({
    this.url,
    this.label,
    this.active,
  });
  FriendBlockListResponseDataUserListLinks.fromJson(Map<String, dynamic> json) {
    url = json["url"]?.toString();
    label = json["label"]?.toString();
    active = json["active"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["url"] = url;
    data["label"] = label;
    data["active"] = active;
    return data;
  }
}

class FriendBlockListResponseDataUserListDataFriend {
/*
{
  "id": 26,
  "name": "Akshay D",
  "email": "Akshay@gmail.com",
  "mobile_number": "5600000000",
  "image": "user/profile/image/IMG-20200621-WA0042-02.jpeg"
}
*/

  int? id;
  String? name;
  String? email;
  String? mobileNumber;
  String? image;

  FriendBlockListResponseDataUserListDataFriend({
    this.id,
    this.name,
    this.email,
    this.mobileNumber,
    this.image,
  });
  FriendBlockListResponseDataUserListDataFriend.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    name = json["name"]?.toString();
    email = json["email"]?.toString();
    mobileNumber = json["mobile_number"]?.toString();
    image = json["image"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["name"] = name;
    data["email"] = email;
    data["mobile_number"] = mobileNumber;
    data["image"] = image;
    return data;
  }
}

class FriendBlockListResponseDataUserListData {
/*
{
  "id": 2,
  "user_id": 22,
  "friend": {
    "id": 26,
    "name": "Akshay D",
    "email": "Akshay@gmail.com",
    "mobile_number": "5600000000",
    "image": "user/profile/image/IMG-20200621-WA0042-02.jpeg"
  },
  "status": true,
  "created_at": "2021-09-17T10:12:47.000000Z",
  "updated_at": "2021-09-17T10:12:47.000000Z",
  "deleted_at": null
}
*/

  int? id;
  int? userId;
  FriendBlockListResponseDataUserListDataFriend? friend;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  FriendBlockListResponseDataUserListData({
    this.id,
    this.userId,
    this.friend,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  FriendBlockListResponseDataUserListData.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    userId = json["user_id"]?.toInt();
    friend = (json["friend"] != null) ? FriendBlockListResponseDataUserListDataFriend.fromJson(json["friend"]) : null;
    status = json["status"];
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    deletedAt = json["deleted_at"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["user_id"] = userId;
    if (friend != null) {
      data["friend"] = friend!.toJson();
    }
    data["status"] = status;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["deleted_at"] = deletedAt;
    return data;
  }
}

class FriendBlockListResponseDataUserList {
/*
{
  "current_page": 1,
  "data": [
    {
      "id": 2,
      "user_id": 22,
      "friend": {
        "id": 26,
        "name": "Akshay D",
        "email": "Akshay@gmail.com",
        "mobile_number": "5600000000",
        "image": "user/profile/image/IMG-20200621-WA0042-02.jpeg"
      },
      "status": true,
      "created_at": "2021-09-17T10:12:47.000000Z",
      "updated_at": "2021-09-17T10:12:47.000000Z",
      "deleted_at": null
    }
  ],
  "first_page_url": "http://192.168.10.8/prof_vanam/public/api/blocks?page=1",
  "from": 1,
  "last_page": 1,
  "last_page_url": "http://192.168.10.8/prof_vanam/public/api/blocks?page=1",
  "links": [
    {
      "url": null,
      "label": "&laquo; Previous",
      "active": false
    }
  ],
  "next_page_url": null,
  "path": "http://192.168.10.8/prof_vanam/public/api/blocks",
  "per_page": 10,
  "prev_page_url": null,
  "to": 1,
  "total": 1
}
*/

  int? currentPage;
  List<FriendBlockListResponseDataUserListData?>? data;
  String? firstPageUrl;
  int? from;
  int? lastPage;
  String? lastPageUrl;
  List<FriendBlockListResponseDataUserListLinks?>? links;
  String? nextPageUrl;
  String? path;
  int? perPage;
  String? prevPageUrl;
  int? to;
  int? total;

  FriendBlockListResponseDataUserList({
    this.currentPage,
    this.data,
    this.firstPageUrl,
    this.from,
    this.lastPage,
    this.lastPageUrl,
    this.links,
    this.nextPageUrl,
    this.path,
    this.perPage,
    this.prevPageUrl,
    this.to,
    this.total,
  });
  FriendBlockListResponseDataUserList.fromJson(Map<String, dynamic> json) {
    currentPage = json["current_page"]?.toInt();
    if (json["data"] != null) {
      final v = json["data"];
      final arr0 = <FriendBlockListResponseDataUserListData>[];
      v.forEach((v) {
        arr0.add(FriendBlockListResponseDataUserListData.fromJson(v));
      });
      this.data = arr0;
    }
    firstPageUrl = json["first_page_url"]?.toString();
    from = json["from"]?.toInt();
    lastPage = json["last_page"]?.toInt();
    lastPageUrl = json["last_page_url"]?.toString();
    if (json["links"] != null) {
      final v = json["links"];
      final arr0 = <FriendBlockListResponseDataUserListLinks>[];
      v.forEach((v) {
        arr0.add(FriendBlockListResponseDataUserListLinks.fromJson(v));
      });
      links = arr0;
    }
    nextPageUrl = json["next_page_url"]?.toString();
    path = json["path"]?.toString();
    perPage = json["per_page"]?.toInt();
    prevPageUrl = json["prev_page_url"]?.toString();
    to = json["to"]?.toInt();
    total = json["total"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["current_page"] = currentPage;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["data"] = arr0;
    }
    data["first_page_url"] = firstPageUrl;
    data["from"] = from;
    data["last_page"] = lastPage;
    data["last_page_url"] = lastPageUrl;
    if (links != null) {
      final v = links;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["links"] = arr0;
    }
    data["next_page_url"] = nextPageUrl;
    data["path"] = path;
    data["per_page"] = perPage;
    data["prev_page_url"] = prevPageUrl;
    data["to"] = to;
    data["total"] = total;
    return data;
  }
}

class FriendBlockListResponseData {
/*
{
  "user_list": {
    "current_page": 1,
    "data": [
      {
        "id": 2,
        "user_id": 22,
        "friend": {
          "id": 26,
          "name": "Akshay D",
          "email": "Akshay@gmail.com",
          "mobile_number": "5600000000",
          "image": "user/profile/image/IMG-20200621-WA0042-02.jpeg"
        },
        "status": true,
        "created_at": "2021-09-17T10:12:47.000000Z",
        "updated_at": "2021-09-17T10:12:47.000000Z",
        "deleted_at": null
      }
    ],
    "first_page_url": "http://192.168.10.8/prof_vanam/public/api/blocks?page=1",
    "from": 1,
    "last_page": 1,
    "last_page_url": "http://192.168.10.8/prof_vanam/public/api/blocks?page=1",
    "links": [
      {
        "url": null,
        "label": "&laquo; Previous",
        "active": false
      }
    ],
    "next_page_url": null,
    "path": "http://192.168.10.8/prof_vanam/public/api/blocks",
    "per_page": 10,
    "prev_page_url": null,
    "to": 1,
    "total": 1
  }
}
*/

  FriendBlockListResponseDataUserList? userList;

  FriendBlockListResponseData({
    this.userList,
  });
  FriendBlockListResponseData.fromJson(Map<String, dynamic> json) {
    userList = (json["user_list"] != null) ? FriendBlockListResponseDataUserList.fromJson(json["user_list"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (userList != null) {
      data["user_list"] = userList!.toJson();
    }
    return data;
  }
}

class FriendBlockListResponse {
/*
{
  "success": true,
  "data": {
    "user_list": {
      "current_page": 1,
      "data": [
        {
          "id": 2,
          "user_id": 22,
          "friend": {
            "id": 26,
            "name": "Akshay D",
            "email": "Akshay@gmail.com",
            "mobile_number": "5600000000",
            "image": "user/profile/image/IMG-20200621-WA0042-02.jpeg"
          },
          "status": true,
          "created_at": "2021-09-17T10:12:47.000000Z",
          "updated_at": "2021-09-17T10:12:47.000000Z",
          "deleted_at": null
        }
      ],
      "first_page_url": "http://192.168.10.8/prof_vanam/public/api/blocks?page=1",
      "from": 1,
      "last_page": 1,
      "last_page_url": "http://192.168.10.8/prof_vanam/public/api/blocks?page=1",
      "links": [
        {
          "url": null,
          "label": "&laquo; Previous",
          "active": false
        }
      ],
      "next_page_url": null,
      "path": "http://192.168.10.8/prof_vanam/public/api/blocks",
      "per_page": 10,
      "prev_page_url": null,
      "to": 1,
      "total": 1
    }
  },
  "message": "Block  list."
}
*/

  bool? success;
  FriendBlockListResponseData? data;
  String? message;

  FriendBlockListResponse({
    this.success,
    this.data,
    this.message,
  });
  FriendBlockListResponse.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    data = (json["data"] != null) ? FriendBlockListResponseData.fromJson(json["data"]) : null;
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["message"] = message;
    return data;
  }
}
