///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class FriendListResponseDataUserListLinks {
/*
{
  "url": null,
  "label": "&laquo; Previous",
  "active": false
}
*/

  String? url;
  String? label;
  bool? active;

  FriendListResponseDataUserListLinks({
    this.url,
    this.label,
    this.active,
  });
  FriendListResponseDataUserListLinks.fromJson(Map<String, dynamic> json) {
    url = json["url"]?.toString();
    label = json["label"]?.toString();
    active = json["active"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["url"] = url;
    data["label"] = label;
    data["active"] = active;
    return data;
  }
}

class Friend {
/*
{
  "id": 1,
  "name": "jayesh",
  "email": "jayesh@test.com",
  "mobile_number": "7304610112",
  "image": null
}
*/

  int? id;
  String? name;
  String? email;
  String? mobileNumber;
  String? image;

  Friend({
    this.id,
    this.name,
    this.email,
    this.mobileNumber,
    this.image,
  });
  Friend.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    name = json["name"]?.toString();
    email = json["email"]?.toString();
    mobileNumber = json["mobile_number"]?.toString();
    image = json["image"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["name"] = name;
    data["email"] = email;
    data["mobile_number"] = mobileNumber;
    data["image"] = image;
    return data;
  }
}

class FriendItem {
/*
{
  "id": 23,
  "friend_by": 22,
  "friend_to": 1,
  "status": true,
  "created_at": "2021-07-23T10:29:11.000000Z",
  "updated_at": "2021-07-23T10:29:11.000000Z",
  "deleted_at": null,
  "friend": {
    "id": 1,
    "name": "jayesh",
    "email": "jayesh@test.com",
    "mobile_number": "7304610112",
    "image": null
  }
}
*/

  int? id;
  int? friendBy;
  int? friendTo;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;
  Friend? friend;

  FriendItem({
    this.id,
    this.friendBy,
    this.friendTo,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
    this.friend,
  });
  FriendItem.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    friendBy = json["friend_by"]?.toInt();
    friendTo = json["friend_to"]?.toInt();
    status = json["status"];
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    deletedAt = json["deleted_at"]?.toString();
    friend = (json["friend"] != null) ? Friend.fromJson(json["friend"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["friend_by"] = friendBy;
    data["friend_to"] = friendTo;
    data["status"] = status;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["deleted_at"] = deletedAt;
    if (friend != null) {
      data["friend"] = friend!.toJson();
    }
    return data;
  }
}

class FriendListResponseDataUserList {
/*
{
  "current_page": 1,
  "data": [
    {
      "id": 23,
      "friend_by": 22,
      "friend_to": 1,
      "status": true,
      "created_at": "2021-07-23T10:29:11.000000Z",
      "updated_at": "2021-07-23T10:29:11.000000Z",
      "deleted_at": null,
      "friend": {
        "id": 1,
        "name": "jayesh",
        "email": "jayesh@test.com",
        "mobile_number": "7304610112",
        "image": null
      }
    }
  ],
  "first_page_url": "http://192.168.10.35/prof_vanam/public/api/friend?page=1",
  "from": 1,
  "last_page": 1,
  "last_page_url": "http://192.168.10.35/prof_vanam/public/api/friend?page=1",
  "links": [
    {
      "url": null,
      "label": "&laquo; Previous",
      "active": false
    }
  ],
  "next_page_url": null,
  "path": "http://192.168.10.35/prof_vanam/public/api/friend",
  "per_page": 10,
  "prev_page_url": null,
  "to": 3,
  "total": 3
}
*/

  int? currentPage;
  List<FriendItem?>? data;
  String? firstPageUrl;
  int? from;
  int? lastPage;
  String? lastPageUrl;
  List<FriendListResponseDataUserListLinks?>? links;
  String? nextPageUrl;
  String? path;
  int? perPage;
  String? prevPageUrl;
  int? to;
  int? total;

  FriendListResponseDataUserList({
    this.currentPage,
    this.data,
    this.firstPageUrl,
    this.from,
    this.lastPage,
    this.lastPageUrl,
    this.links,
    this.nextPageUrl,
    this.path,
    this.perPage,
    this.prevPageUrl,
    this.to,
    this.total,
  });
  FriendListResponseDataUserList.fromJson(Map<String, dynamic> json) {
    currentPage = json["current_page"]?.toInt();
    if (json["data"] != null) {
      final v = json["data"];
      final arr0 = <FriendItem>[];
      v.forEach((v) {
        arr0.add(FriendItem.fromJson(v));
      });
      this.data = arr0;
    }
    firstPageUrl = json["first_page_url"]?.toString();
    from = json["from"]?.toInt();
    lastPage = json["last_page"]?.toInt();
    lastPageUrl = json["last_page_url"]?.toString();
    if (json["links"] != null) {
      final v = json["links"];
      final arr0 = <FriendListResponseDataUserListLinks>[];
      v.forEach((v) {
        arr0.add(FriendListResponseDataUserListLinks.fromJson(v));
      });
      links = arr0;
    }
    nextPageUrl = json["next_page_url"]?.toString();
    path = json["path"]?.toString();
    perPage = json["per_page"]?.toInt();
    prevPageUrl = json["prev_page_url"]?.toString();
    to = json["to"]?.toInt();
    total = json["total"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["current_page"] = currentPage;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["data"] = arr0;
    }
    data["first_page_url"] = firstPageUrl;
    data["from"] = from;
    data["last_page"] = lastPage;
    data["last_page_url"] = lastPageUrl;
    if (links != null) {
      final v = links;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["links"] = arr0;
    }
    data["next_page_url"] = nextPageUrl;
    data["path"] = path;
    data["per_page"] = perPage;
    data["prev_page_url"] = prevPageUrl;
    data["to"] = to;
    data["total"] = total;
    return data;
  }
}

class FriendListResponseData {
/*
{
  "user_list": {
    "current_page": 1,
    "data": [
      {
        "id": 23,
        "friend_by": 22,
        "friend_to": 1,
        "status": true,
        "created_at": "2021-07-23T10:29:11.000000Z",
        "updated_at": "2021-07-23T10:29:11.000000Z",
        "deleted_at": null,
        "friend": {
          "id": 1,
          "name": "jayesh",
          "email": "jayesh@test.com",
          "mobile_number": "7304610112",
          "image": null
        }
      }
    ],
    "first_page_url": "http://192.168.10.35/prof_vanam/public/api/friend?page=1",
    "from": 1,
    "last_page": 1,
    "last_page_url": "http://192.168.10.35/prof_vanam/public/api/friend?page=1",
    "links": [
      {
        "url": null,
        "label": "&laquo; Previous",
        "active": false
      }
    ],
    "next_page_url": null,
    "path": "http://192.168.10.35/prof_vanam/public/api/friend",
    "per_page": 10,
    "prev_page_url": null,
    "to": 3,
    "total": 3
  }
}
*/

  FriendListResponseDataUserList? userList;

  FriendListResponseData({
    this.userList,
  });
  FriendListResponseData.fromJson(Map<String, dynamic> json) {
    userList = (json["user_list"] != null) ? FriendListResponseDataUserList.fromJson(json["user_list"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (userList != null) {
      data["user_list"] = userList!.toJson();
    }
    return data;
  }
}

class FriendListResponse {
/*
{
  "success": true,
  "data": {
    "user_list": {
      "current_page": 1,
      "data": [
        {
          "id": 23,
          "friend_by": 22,
          "friend_to": 1,
          "status": true,
          "created_at": "2021-07-23T10:29:11.000000Z",
          "updated_at": "2021-07-23T10:29:11.000000Z",
          "deleted_at": null,
          "friend": {
            "id": 1,
            "name": "jayesh",
            "email": "jayesh@test.com",
            "mobile_number": "7304610112",
            "image": null
          }
        }
      ],
      "first_page_url": "http://192.168.10.35/prof_vanam/public/api/friend?page=1",
      "from": 1,
      "last_page": 1,
      "last_page_url": "http://192.168.10.35/prof_vanam/public/api/friend?page=1",
      "links": [
        {
          "url": null,
          "label": "&laquo; Previous",
          "active": false
        }
      ],
      "next_page_url": null,
      "path": "http://192.168.10.35/prof_vanam/public/api/friend",
      "per_page": 10,
      "prev_page_url": null,
      "to": 3,
      "total": 3
    }
  },
  "message": "Friend  list."
}
*/

  bool? success;
  FriendListResponseData? data;
  String? message;

  FriendListResponse({
    this.success,
    this.data,
    this.message,
  });
  FriendListResponse.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    data = (json["data"] != null) ? FriendListResponseData.fromJson(json["data"]) : null;
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["message"] = message;
    return data;
  }
}
