///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class FriendDetailResponseDataUserUserBasicInfo {
/*
{
  "id": 4,
  "user_id": 22,
  "home_city": "pune1",
  "current_city": "satara",
  "gender": "Other",
  "language": "sgdfg, dfgdf, dfg",
  "interests": "dgdfg",
  "relationship": "Other",
  "dob": "2001-01-11",
  "image": "user/profile/image/IMG_20210916_111325.jpg",
  "status": true,
  "created_at": "2021-07-24T06:45:07.000000Z",
  "updated_at": "2021-09-16T08:40:09.000000Z",
  "deleted_at": null
}
*/

  int? id;
  int? userId;
  String? homeCity;
  String? currentCity;
  String? gender;
  String? language;
  String? interests;
  String? relationship;
  String? dob;
  String? image;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  FriendDetailResponseDataUserUserBasicInfo({
    this.id,
    this.userId,
    this.homeCity,
    this.currentCity,
    this.gender,
    this.language,
    this.interests,
    this.relationship,
    this.dob,
    this.image,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  FriendDetailResponseDataUserUserBasicInfo.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    userId = json["user_id"]?.toInt();
    homeCity = json["home_city"]?.toString();
    currentCity = json["current_city"]?.toString();
    gender = json["gender"]?.toString();
    language = json["language"]?.toString();
    interests = json["interests"]?.toString();
    relationship = json["relationship"]?.toString();
    dob = json["dob"]?.toString();
    image = json["image"]?.toString();
    status = json["status"];
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    deletedAt = json["deleted_at"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["user_id"] = userId;
    data["home_city"] = homeCity;
    data["current_city"] = currentCity;
    data["gender"] = gender;
    data["language"] = language;
    data["interests"] = interests;
    data["relationship"] = relationship;
    data["dob"] = dob;
    data["image"] = image;
    data["status"] = status;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["deleted_at"] = deletedAt;
    return data;
  }
}

class FriendDetailResponseDataUser {
/*
{
  "id": 22,
  "image": "user/profile/image/IMG_20210916_111325.jpg",
  "name": "jayesh",
  "email": "shinde@gmail.com",
  "gender": "Male",
  "mobile_number": "7304610113",
  "email_verified_at": null,
  "type": "customer",
  "status": true,
  "created_at": "2021-07-23T09:59:32.000000Z",
  "updated_at": "2021-09-17T09:31:31.000000Z",
  "deleted_at": null,
  "device_key": "czlQN5awSiCXpA9eGa6AWb:APA91bGxn6l-2vy9RAoL48neH387AnnGqSeA68R0x-vhhH6olm_w2J_MZQhTuV9HuZnqNUgBH8PODa2KAdxe5P8-3yaP7QNQhPZy-uYCcm8XIBkUx08gmZWjLh1uHLnzZCvCApWD5Svu",
  "device_token": null,
  "connection_count": 3,
  "user_basic_info": {
    "id": 4,
    "user_id": 22,
    "home_city": "pune1",
    "current_city": "satara",
    "gender": "Other",
    "language": "sgdfg, dfgdf, dfg",
    "interests": "dgdfg",
    "relationship": "Other",
    "dob": "2001-01-11",
    "image": "user/profile/image/IMG_20210916_111325.jpg",
    "status": true,
    "created_at": "2021-07-24T06:45:07.000000Z",
    "updated_at": "2021-09-16T08:40:09.000000Z",
    "deleted_at": null
  }
}
*/

  int? id;
  String? image;
  String? name;
  String? email;
  String? gender;
  String? mobileNumber;
  String? emailVerifiedAt;
  String? type;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;
  String? deviceKey;
  String? deviceToken;
  int? connectionCount;
  FriendDetailResponseDataUserUserBasicInfo? userBasicInfo;

  FriendDetailResponseDataUser({
    this.id,
    this.image,
    this.name,
    this.email,
    this.gender,
    this.mobileNumber,
    this.emailVerifiedAt,
    this.type,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
    this.deviceKey,
    this.deviceToken,
    this.connectionCount,
    this.userBasicInfo,
  });
  FriendDetailResponseDataUser.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    image = json["image"]?.toString();
    name = json["name"]?.toString();
    email = json["email"]?.toString();
    gender = json["gender"]?.toString();
    mobileNumber = json["mobile_number"]?.toString();
    emailVerifiedAt = json["email_verified_at"]?.toString();
    type = json["type"]?.toString();
    status = json["status"];
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    deletedAt = json["deleted_at"]?.toString();
    deviceKey = json["device_key"]?.toString();
    deviceToken = json["device_token"]?.toString();
    connectionCount = json["connection_count"]?.toInt();
    userBasicInfo = (json["user_basic_info"] != null) ? FriendDetailResponseDataUserUserBasicInfo.fromJson(json["user_basic_info"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["image"] = image;
    data["name"] = name;
    data["email"] = email;
    data["gender"] = gender;
    data["mobile_number"] = mobileNumber;
    data["email_verified_at"] = emailVerifiedAt;
    data["type"] = type;
    data["status"] = status;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["deleted_at"] = deletedAt;
    data["device_key"] = deviceKey;
    data["device_token"] = deviceToken;
    data["connection_count"] = connectionCount;
    if (userBasicInfo != null) {
      data["user_basic_info"] = userBasicInfo!.toJson();
    }
    return data;
  }
}

class FriendDetailResponseData {
/*
{
  "user": {
    "id": 22,
    "image": "user/profile/image/IMG_20210916_111325.jpg",
    "name": "jayesh",
    "email": "shinde@gmail.com",
    "gender": "Male",
    "mobile_number": "7304610113",
    "email_verified_at": null,
    "type": "customer",
    "status": true,
    "created_at": "2021-07-23T09:59:32.000000Z",
    "updated_at": "2021-09-17T09:31:31.000000Z",
    "deleted_at": null,
    "device_key": "czlQN5awSiCXpA9eGa6AWb:APA91bGxn6l-2vy9RAoL48neH387AnnGqSeA68R0x-vhhH6olm_w2J_MZQhTuV9HuZnqNUgBH8PODa2KAdxe5P8-3yaP7QNQhPZy-uYCcm8XIBkUx08gmZWjLh1uHLnzZCvCApWD5Svu",
    "device_token": null,
    "connection_count": 3,
    "user_basic_info": {
      "id": 4,
      "user_id": 22,
      "home_city": "pune1",
      "current_city": "satara",
      "gender": "Other",
      "language": "sgdfg, dfgdf, dfg",
      "interests": "dgdfg",
      "relationship": "Other",
      "dob": "2001-01-11",
      "image": "user/profile/image/IMG_20210916_111325.jpg",
      "status": true,
      "created_at": "2021-07-24T06:45:07.000000Z",
      "updated_at": "2021-09-16T08:40:09.000000Z",
      "deleted_at": null
    }
  },
  "friend": 0,
  "friend_block": 1
}
*/

  FriendDetailResponseDataUser? user;
  int? friend;
  int? friendBlock;

  FriendDetailResponseData({
    this.user,
    this.friend,
    this.friendBlock,
  });
  FriendDetailResponseData.fromJson(Map<String, dynamic> json) {
    user = (json["user"] != null) ? FriendDetailResponseDataUser.fromJson(json["user"]) : null;
    friend = json["friend"]?.toInt();
    friendBlock = json["friend_block"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (user != null) {
      data["user"] = user!.toJson();
    }
    data["friend"] = friend;
    data["friend_block"] = friendBlock;
    return data;
  }
}

class FriendDetailResponse {
/*
{
  "success": true,
  "data": {
    "user": {
      "id": 22,
      "image": "user/profile/image/IMG_20210916_111325.jpg",
      "name": "jayesh",
      "email": "shinde@gmail.com",
      "gender": "Male",
      "mobile_number": "7304610113",
      "email_verified_at": null,
      "type": "customer",
      "status": true,
      "created_at": "2021-07-23T09:59:32.000000Z",
      "updated_at": "2021-09-17T09:31:31.000000Z",
      "deleted_at": null,
      "device_key": "czlQN5awSiCXpA9eGa6AWb:APA91bGxn6l-2vy9RAoL48neH387AnnGqSeA68R0x-vhhH6olm_w2J_MZQhTuV9HuZnqNUgBH8PODa2KAdxe5P8-3yaP7QNQhPZy-uYCcm8XIBkUx08gmZWjLh1uHLnzZCvCApWD5Svu",
      "device_token": null,
      "connection_count": 3,
      "user_basic_info": {
        "id": 4,
        "user_id": 22,
        "home_city": "pune1",
        "current_city": "satara",
        "gender": "Other",
        "language": "sgdfg, dfgdf, dfg",
        "interests": "dgdfg",
        "relationship": "Other",
        "dob": "2001-01-11",
        "image": "user/profile/image/IMG_20210916_111325.jpg",
        "status": true,
        "created_at": "2021-07-24T06:45:07.000000Z",
        "updated_at": "2021-09-16T08:40:09.000000Z",
        "deleted_at": null
      }
    },
    "friend": 0,
    "friend_block": 1
  },
  "message": "User Detail."
}
*/

  bool? success;
  FriendDetailResponseData? data;
  String? message;

  FriendDetailResponse({
    this.success,
    this.data,
    this.message,
  });
  FriendDetailResponse.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    data = (json["data"] != null) ? FriendDetailResponseData.fromJson(json["data"]) : null;
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["message"] = message;
    return data;
  }
}
