///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ConnectionAcceptListResponseDataUserListLinks {
/*
{
  "url": null,
  "label": "&laquo; Previous",
  "active": false
}
*/

  String? url;
  String? label;
  bool? active;

  ConnectionAcceptListResponseDataUserListLinks({
    this.url,
    this.label,
    this.active,
  });
  ConnectionAcceptListResponseDataUserListLinks.fromJson(Map<String, dynamic> json) {
    url = json["url"]?.toString();
    label = json["label"]?.toString();
    active = json["active"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["url"] = url;
    data["label"] = label;
    data["active"] = active;
    return data;
  }
}

class ConnectionAcceptListResponseDataUserListDataUser {
/*
{
  "id": 6,
  "name": "Grishma",
  "email": "Grishma@gmail.com",
  "mobile_number": "7620672068",
  "image": "user/profile/image/B612_20190118_142224_000.jpg"
}
*/

  int? id;
  String? name;
  String? email;
  String? mobileNumber;
  String? image;

  ConnectionAcceptListResponseDataUserListDataUser({
    this.id,
    this.name,
    this.email,
    this.mobileNumber,
    this.image,
  });
  ConnectionAcceptListResponseDataUserListDataUser.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    name = json["name"]?.toString();
    email = json["email"]?.toString();
    mobileNumber = json["mobile_number"]?.toString();
    image = json["image"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["name"] = name;
    data["email"] = email;
    data["mobile_number"] = mobileNumber;
    data["image"] = image;
    return data;
  }
}

class ConnectionAcceptListResponseDataUserListData {
/*
{
  "id": 67,
  "user_id": 6,
  "friend_id": 5,
  "connect_status": 1,
  "status": true,
  "created_at": "2021-09-24T06:28:56.000000Z",
  "updated_at": "2021-09-24T06:28:56.000000Z",
  "deleted_at": null,
  "user": {
    "id": 6,
    "name": "Grishma",
    "email": "Grishma@gmail.com",
    "mobile_number": "7620672068",
    "image": "user/profile/image/B612_20190118_142224_000.jpg"
  }
}
*/

  int? id;
  int? userId;
  int? friendId;
  int? connectStatus;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;
  ConnectionAcceptListResponseDataUserListDataUser? user;

  ConnectionAcceptListResponseDataUserListData({
    this.id,
    this.userId,
    this.friendId,
    this.connectStatus,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
    this.user,
  });
  ConnectionAcceptListResponseDataUserListData.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    userId = json["user_id"]?.toInt();
    friendId = json["friend_id"]?.toInt();
    connectStatus = json["connect_status"]?.toInt();
    status = json["status"];
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    deletedAt = json["deleted_at"]?.toString();
    user = (json["user"] != null) ? ConnectionAcceptListResponseDataUserListDataUser.fromJson(json["user"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["user_id"] = userId;
    data["friend_id"] = friendId;
    data["connect_status"] = connectStatus;
    data["status"] = status;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["deleted_at"] = deletedAt;
    if (user != null) {
      data["user"] = user!.toJson();
    }
    return data;
  }
}

class ConnectionAcceptListResponseDataUserList {
/*
{
  "current_page": 1,
  "data": [
    {
      "id": 67,
      "user_id": 6,
      "friend_id": 5,
      "connect_status": 1,
      "status": true,
      "created_at": "2021-09-24T06:28:56.000000Z",
      "updated_at": "2021-09-24T06:28:56.000000Z",
      "deleted_at": null,
      "user": {
        "id": 6,
        "name": "Grishma",
        "email": "Grishma@gmail.com",
        "mobile_number": "7620672068",
        "image": "user/profile/image/B612_20190118_142224_000.jpg"
      }
    }
  ],
  "first_page_url": "http://192.168.10.8/prof_vanam/public/api/conection-accept?page=1",
  "from": 1,
  "last_page": 1,
  "last_page_url": "http://192.168.10.8/prof_vanam/public/api/conection-accept?page=1",
  "links": [
    {
      "url": null,
      "label": "&laquo; Previous",
      "active": false
    }
  ],
  "next_page_url": null,
  "path": "http://192.168.10.8/prof_vanam/public/api/conection-accept",
  "per_page": 10,
  "prev_page_url": null,
  "to": 1,
  "total": 1
}
*/

  int? currentPage;
  List<ConnectionAcceptListResponseDataUserListData?>? data;
  String? firstPageUrl;
  int? from;
  int? lastPage;
  String? lastPageUrl;
  List<ConnectionAcceptListResponseDataUserListLinks?>? links;
  String? nextPageUrl;
  String? path;
  int? perPage;
  String? prevPageUrl;
  int? to;
  int? total;

  ConnectionAcceptListResponseDataUserList({
    this.currentPage,
    this.data,
    this.firstPageUrl,
    this.from,
    this.lastPage,
    this.lastPageUrl,
    this.links,
    this.nextPageUrl,
    this.path,
    this.perPage,
    this.prevPageUrl,
    this.to,
    this.total,
  });
  ConnectionAcceptListResponseDataUserList.fromJson(Map<String, dynamic> json) {
    currentPage = json["current_page"]?.toInt();
    if (json["data"] != null) {
      final v = json["data"];
      final arr0 = <ConnectionAcceptListResponseDataUserListData>[];
      v.forEach((v) {
        arr0.add(ConnectionAcceptListResponseDataUserListData.fromJson(v));
      });
      this.data = arr0;
    }
    firstPageUrl = json["first_page_url"]?.toString();
    from = json["from"]?.toInt();
    lastPage = json["last_page"]?.toInt();
    lastPageUrl = json["last_page_url"]?.toString();
    if (json["links"] != null) {
      final v = json["links"];
      final arr0 = <ConnectionAcceptListResponseDataUserListLinks>[];
      v.forEach((v) {
        arr0.add(ConnectionAcceptListResponseDataUserListLinks.fromJson(v));
      });
      links = arr0;
    }
    nextPageUrl = json["next_page_url"]?.toString();
    path = json["path"]?.toString();
    perPage = json["per_page"]?.toInt();
    prevPageUrl = json["prev_page_url"]?.toString();
    to = json["to"]?.toInt();
    total = json["total"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["current_page"] = currentPage;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["data"] = arr0;
    }
    data["first_page_url"] = firstPageUrl;
    data["from"] = from;
    data["last_page"] = lastPage;
    data["last_page_url"] = lastPageUrl;
    if (links != null) {
      final v = links;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["links"] = arr0;
    }
    data["next_page_url"] = nextPageUrl;
    data["path"] = path;
    data["per_page"] = perPage;
    data["prev_page_url"] = prevPageUrl;
    data["to"] = to;
    data["total"] = total;
    return data;
  }
}

class ConnectionAcceptListResponseData {
/*
{
  "user_list": {
    "current_page": 1,
    "data": [
      {
        "id": 67,
        "user_id": 6,
        "friend_id": 5,
        "connect_status": 1,
        "status": true,
        "created_at": "2021-09-24T06:28:56.000000Z",
        "updated_at": "2021-09-24T06:28:56.000000Z",
        "deleted_at": null,
        "user": {
          "id": 6,
          "name": "Grishma",
          "email": "Grishma@gmail.com",
          "mobile_number": "7620672068",
          "image": "user/profile/image/B612_20190118_142224_000.jpg"
        }
      }
    ],
    "first_page_url": "http://192.168.10.8/prof_vanam/public/api/conection-accept?page=1",
    "from": 1,
    "last_page": 1,
    "last_page_url": "http://192.168.10.8/prof_vanam/public/api/conection-accept?page=1",
    "links": [
      {
        "url": null,
        "label": "&laquo; Previous",
        "active": false
      }
    ],
    "next_page_url": null,
    "path": "http://192.168.10.8/prof_vanam/public/api/conection-accept",
    "per_page": 10,
    "prev_page_url": null,
    "to": 1,
    "total": 1
  }
}
*/

  ConnectionAcceptListResponseDataUserList? userList;

  ConnectionAcceptListResponseData({
    this.userList,
  });
  ConnectionAcceptListResponseData.fromJson(Map<String, dynamic> json) {
    userList = (json["user_list"] != null) ? ConnectionAcceptListResponseDataUserList.fromJson(json["user_list"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (userList != null) {
      data["user_list"] = userList!.toJson();
    }
    return data;
  }
}

class ConnectionAcceptListResponse {
/*
{
  "success": true,
  "data": {
    "user_list": {
      "current_page": 1,
      "data": [
        {
          "id": 67,
          "user_id": 6,
          "friend_id": 5,
          "connect_status": 1,
          "status": true,
          "created_at": "2021-09-24T06:28:56.000000Z",
          "updated_at": "2021-09-24T06:28:56.000000Z",
          "deleted_at": null,
          "user": {
            "id": 6,
            "name": "Grishma",
            "email": "Grishma@gmail.com",
            "mobile_number": "7620672068",
            "image": "user/profile/image/B612_20190118_142224_000.jpg"
          }
        }
      ],
      "first_page_url": "http://192.168.10.8/prof_vanam/public/api/conection-accept?page=1",
      "from": 1,
      "last_page": 1,
      "last_page_url": "http://192.168.10.8/prof_vanam/public/api/conection-accept?page=1",
      "links": [
        {
          "url": null,
          "label": "&laquo; Previous",
          "active": false
        }
      ],
      "next_page_url": null,
      "path": "http://192.168.10.8/prof_vanam/public/api/conection-accept",
      "per_page": 10,
      "prev_page_url": null,
      "to": 1,
      "total": 1
    }
  },
  "message": "Connection  list."
}
*/

  bool? success;
  ConnectionAcceptListResponseData? data;
  String? message;

  ConnectionAcceptListResponse({
    this.success,
    this.data,
    this.message,
  });
  ConnectionAcceptListResponse.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    data = (json["data"] != null) ? ConnectionAcceptListResponseData.fromJson(json["data"]) : null;
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["message"] = message;
    return data;
  }
}
