///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ChangePasswordResponse {
/*
{
  "success": true,
  "data": true,
  "message": "Password Change Successfully."
}
*/

  bool? success;
  bool? data;
  String? message;

  ChangePasswordResponse({
    this.success,
    this.data,
    this.message,
  });
  ChangePasswordResponse.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    data = json["data"];
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    data["data"] = this.data;
    data["message"] = message;
    return data;
  }
}
