///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PostListResponseDataPostListLinks {
/*
{
  "url": null,
  "label": "&laquo; Previous",
  "active": false
}
*/

  String? url;
  String? label;
  bool? active;

  PostListResponseDataPostListLinks({
    this.url,
    this.label,
    this.active,
  });
  PostListResponseDataPostListLinks.fromJson(Map<String, dynamic> json) {
    url = json["url"]?.toString();
    label = json["label"]?.toString();
    active = json["active"];
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["url"] = url;
    data["label"] = label;
    data["active"] = active;
    return data;
  }
}

class PostListResponseDataPostListDataGroup {
/*
{
  "id": 15,
  "name": "new group by Grishma"
}
*/

  int? id;
  String? name;

  PostListResponseDataPostListDataGroup({
    this.id,
    this.name,
  });
  PostListResponseDataPostListDataGroup.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    name = json["name"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["name"] = name;
    return data;
  }
}

class PostListResponseDataPostListDataSharePostShareBy {
/*
{
  "id": 4,
  "image": "user/profile/image/MyEmoji_20210617_224544_3896.gif",
  "name": "jayesh",
  "email": "jayesh@test.com",
  "gender": "male",
  "mobile_number": "7304610113",
  "email_verified_at": null,
  "type": "customer",
  "status": true,
  "created_at": "2021-09-24T06:21:52.000000Z",
  "updated_at": "2021-09-27T09:02:25.000000Z",
  "deleted_at": null,
  "device_key": "eVveLzCaQvOLtD_UK3PIFs:APA91bEFL0m0LuQnHtbYWS6yhO656G_GJFMbiwwFHuK9iFIuRx6ZiYXATj8bN8PPq2mLfKrAimm0GSLlsayi9CNy9-n7HSDk7R8SWnSMz8d8tGdSTigHGmuyBHxUDlTb30nLdIK1SDnI",
  "device_token": null
}
*/

  int? id;
  String? image;
  String? name;
  String? email;
  String? gender;
  String? mobileNumber;
  String? emailVerifiedAt;
  String? type;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;
  String? deviceKey;
  String? deviceToken;

  PostListResponseDataPostListDataSharePostShareBy({
    this.id,
    this.image,
    this.name,
    this.email,
    this.gender,
    this.mobileNumber,
    this.emailVerifiedAt,
    this.type,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
    this.deviceKey,
    this.deviceToken,
  });
  PostListResponseDataPostListDataSharePostShareBy.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    image = json["image"]?.toString();
    name = json["name"]?.toString();
    email = json["email"]?.toString();
    gender = json["gender"]?.toString();
    mobileNumber = json["mobile_number"]?.toString();
    emailVerifiedAt = json["email_verified_at"]?.toString();
    type = json["type"]?.toString();
    status = json["status"];
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    deletedAt = json["deleted_at"]?.toString();
    deviceKey = json["device_key"]?.toString();
    deviceToken = json["device_token"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["image"] = image;
    data["name"] = name;
    data["email"] = email;
    data["gender"] = gender;
    data["mobile_number"] = mobileNumber;
    data["email_verified_at"] = emailVerifiedAt;
    data["type"] = type;
    data["status"] = status;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["deleted_at"] = deletedAt;
    data["device_key"] = deviceKey;
    data["device_token"] = deviceToken;
    return data;
  }
}

class PostListResponseDataPostListDataSharePost {
/*
{
  "id": 32,
  "share_by": {
    "id": 4,
    "image": "user/profile/image/MyEmoji_20210617_224544_3896.gif",
    "name": "jayesh",
    "email": "jayesh@test.com",
    "gender": "male",
    "mobile_number": "7304610113",
    "email_verified_at": null,
    "type": "customer",
    "status": true,
    "created_at": "2021-09-24T06:21:52.000000Z",
    "updated_at": "2021-09-27T09:02:25.000000Z",
    "deleted_at": null,
    "device_key": "eVveLzCaQvOLtD_UK3PIFs:APA91bEFL0m0LuQnHtbYWS6yhO656G_GJFMbiwwFHuK9iFIuRx6ZiYXATj8bN8PPq2mLfKrAimm0GSLlsayi9CNy9-n7HSDk7R8SWnSMz8d8tGdSTigHGmuyBHxUDlTb30nLdIK1SDnI",
    "device_token": null
  },
  "share_to": 4,
  "post_id": 130,
  "name": "test ooist",
  "status": true,
  "created_at": "2021-09-27T09:55:05.000000Z",
  "updated_at": "2021-09-27T09:55:05.000000Z",
  "deleted_at": null
}
*/

  int? id;
  PostListResponseDataPostListDataSharePostShareBy? shareBy;
  int? shareTo;
  int? postId;
  String? name;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  PostListResponseDataPostListDataSharePost({
    this.id,
    this.shareBy,
    this.shareTo,
    this.postId,
    this.name,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  PostListResponseDataPostListDataSharePost.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    shareBy = (json["share_by"] != null) ? PostListResponseDataPostListDataSharePostShareBy.fromJson(json["share_by"]) : null;
    shareTo = json["share_to"]?.toInt();
    postId = json["post_id"]?.toInt();
    name = json["name"]?.toString();
    status = json["status"];
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    deletedAt = json["deleted_at"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    if (shareBy != null) {
      data["share_by"] = shareBy!.toJson();
    }
    data["share_to"] = shareTo;
    data["post_id"] = postId;
    data["name"] = name;
    data["status"] = status;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["deleted_at"] = deletedAt;
    return data;
  }
}

class PostListResponseDataPostListDataPostCount {
/*
{
  "id": 78,
  "post_id": 130,
  "like": 1,
  "favoirate": 0,
  "comment": 1,
  "share": 0,
  "created_at": "2021-09-27T09:55:17.000000Z",
  "updated_at": "2021-09-27T09:55:26.000000Z",
  "deleted_at": null
}
*/

  int? id;
  int? postId;
  int? like;
  int? favoirate;
  int? comment;
  int? share;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  PostListResponseDataPostListDataPostCount({
    this.id,
    this.postId,
    this.like,
    this.favoirate,
    this.comment,
    this.share,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  PostListResponseDataPostListDataPostCount.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    postId = json["post_id"]?.toInt();
    like = json["like"]?.toInt();
    favoirate = json["favoirate"]?.toInt();
    comment = json["comment"]?.toInt();
    share = json["share"]?.toInt();
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    deletedAt = json["deleted_at"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["post_id"] = postId;
    data["like"] = like;
    data["favoirate"] = favoirate;
    data["comment"] = comment;
    data["share"] = share;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["deleted_at"] = deletedAt;
    return data;
  }
}

class PostListResponseDataPostListDataPostUserCount {
/*
{
  "id": 53,
  "user_id": 4,
  "post_id": 130,
  "like": 1,
  "favoirate": 0,
  "created_at": "2021-09-27T09:55:17.000000Z",
  "updated_at": "2021-09-27T09:55:17.000000Z",
  "deleted_at": null
}
*/

  int? id;
  int? userId;
  int? postId;
  int? like;
  int? favoirate;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  PostListResponseDataPostListDataPostUserCount({
    this.id,
    this.userId,
    this.postId,
    this.like,
    this.favoirate,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  PostListResponseDataPostListDataPostUserCount.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    userId = json["user_id"]?.toInt();
    postId = json["post_id"]?.toInt();
    like = json["like"]?.toInt();
    favoirate = json["favoirate"]?.toInt();
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    deletedAt = json["deleted_at"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["user_id"] = userId;
    data["post_id"] = postId;
    data["like"] = like;
    data["favoirate"] = favoirate;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["deleted_at"] = deletedAt;
    return data;
  }
}

class PostListResponseDataPostListDataUser {
/*
{
  "id": 4,
  "name": "jayesh",
  "email": "jayesh@test.com",
  "mobile_number": "7304610113",
  "image": "user/profile/image/MyEmoji_20210617_224544_3896.gif"
}
*/

  int? id;
  String? name;
  String? email;
  String? mobileNumber;
  String? image;

  PostListResponseDataPostListDataUser({
    this.id,
    this.name,
    this.email,
    this.mobileNumber,
    this.image,
  });
  PostListResponseDataPostListDataUser.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    name = json["name"]?.toString();
    email = json["email"]?.toString();
    mobileNumber = json["mobile_number"]?.toString();
    image = json["image"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["name"] = name;
    data["email"] = email;
    data["mobile_number"] = mobileNumber;
    data["image"] = image;
    return data;
  }
}

class PostListResponseDataPostListDataPostImage {
/*
{
  "id": 61,
  "post_id": 130,
  "url": "user/post/image/IMG_20210927_152100.jpg",
  "status": true,
  "created_at": "2021-09-27T09:54:36.000000Z",
  "updated_at": "2021-09-27T09:54:36.000000Z",
  "deleted_at": null
}
*/

  int? id;
  int? postId;
  String? url;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;

  PostListResponseDataPostListDataPostImage({
    this.id,
    this.postId,
    this.url,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
  });
  PostListResponseDataPostListDataPostImage.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    postId = json["post_id"]?.toInt();
    url = json["url"]?.toString();
    status = json["status"];
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    deletedAt = json["deleted_at"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["post_id"] = postId;
    data["url"] = url;
    data["status"] = status;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["deleted_at"] = deletedAt;
    return data;
  }
}

class PostListResponseDataPostListData {
/*
{
  "id": 130,
  "user_id": 4,
  "group_id": 15,
  "share_id": 1,
  "content": "sample post",
  "url": null,
  "status": true,
  "created_at": "2021-09-27T09:54:36.000000Z",
  "updated_at": "2021-09-27T09:54:36.000000Z",
  "deleted_at": null,
  "post_video": [
    null
  ],
  "post_image": [
    {
      "id": 61,
      "post_id": 130,
      "url": "user/post/image/IMG_20210927_152100.jpg",
      "status": true,
      "created_at": "2021-09-27T09:54:36.000000Z",
      "updated_at": "2021-09-27T09:54:36.000000Z",
      "deleted_at": null
    }
  ],
  "user": {
    "id": 4,
    "name": "jayesh",
    "email": "jayesh@test.com",
    "mobile_number": "7304610113",
    "image": "user/profile/image/MyEmoji_20210617_224544_3896.gif"
  },
  "post_user_count": {
    "id": 53,
    "user_id": 4,
    "post_id": 130,
    "like": 1,
    "favoirate": 0,
    "created_at": "2021-09-27T09:55:17.000000Z",
    "updated_at": "2021-09-27T09:55:17.000000Z",
    "deleted_at": null
  },
  "post_count": {
    "id": 78,
    "post_id": 130,
    "like": 1,
    "favoirate": 0,
    "comment": 1,
    "share": 0,
    "created_at": "2021-09-27T09:55:17.000000Z",
    "updated_at": "2021-09-27T09:55:26.000000Z",
    "deleted_at": null
  },
  "share_post": {
    "id": 32,
    "share_by": {
      "id": 4,
      "image": "user/profile/image/MyEmoji_20210617_224544_3896.gif",
      "name": "jayesh",
      "email": "jayesh@test.com",
      "gender": "male",
      "mobile_number": "7304610113",
      "email_verified_at": null,
      "type": "customer",
      "status": true,
      "created_at": "2021-09-24T06:21:52.000000Z",
      "updated_at": "2021-09-27T09:02:25.000000Z",
      "deleted_at": null,
      "device_key": "eVveLzCaQvOLtD_UK3PIFs:APA91bEFL0m0LuQnHtbYWS6yhO656G_GJFMbiwwFHuK9iFIuRx6ZiYXATj8bN8PPq2mLfKrAimm0GSLlsayi9CNy9-n7HSDk7R8SWnSMz8d8tGdSTigHGmuyBHxUDlTb30nLdIK1SDnI",
      "device_token": null
    },
    "share_to": 4,
    "post_id": 130,
    "name": "test ooist",
    "status": true,
    "created_at": "2021-09-27T09:55:05.000000Z",
    "updated_at": "2021-09-27T09:55:05.000000Z",
    "deleted_at": null
  },
  "group": {
    "id": 15,
    "name": "new group by Grishma"
  }
}
*/

  int? id;
  int? userId;
  int? groupId;
  int? shareId;
  String? content;
  String? url;
  bool? status;
  String? createdAt;
  String? updatedAt;
  String? deletedAt;
  List<PostListResponseDataPostListDataPostImage?>? postVideo;
  List<PostListResponseDataPostListDataPostImage?>? postImage;
  PostListResponseDataPostListDataUser? user;
  PostListResponseDataPostListDataPostUserCount? postUserCount;
  PostListResponseDataPostListDataPostCount? postCount;
  PostListResponseDataPostListDataSharePost? sharePost;
  PostListResponseDataPostListDataGroup? group;

  PostListResponseDataPostListData({
    this.id,
    this.userId,
    this.groupId,
    this.shareId,
    this.content,
    this.url,
    this.status,
    this.createdAt,
    this.updatedAt,
    this.deletedAt,
    this.postVideo,
    this.postImage,
    this.user,
    this.postUserCount,
    this.postCount,
    this.sharePost,
    this.group,
  });
  PostListResponseDataPostListData.fromJson(Map<String, dynamic> json) {
    id = json["id"]?.toInt();
    userId = json["user_id"]?.toInt();
    groupId = json["group_id"]?.toInt();
    shareId = json["share_id"]?.toInt();
    content = json["content"]?.toString();
    url = json["url"]?.toString();
    status = json["status"];
    createdAt = json["created_at"]?.toString();
    updatedAt = json["updated_at"]?.toString();
    deletedAt = json["deleted_at"]?.toString();

    if (json["post_image"] != null) {
    final v = json["post_image"];
    final arr0 = <PostListResponseDataPostListDataPostImage>[];
    v.forEach((v) {
    arr0.add(PostListResponseDataPostListDataPostImage.fromJson(v));
    });
    postImage = arr0;
    }
    user = (json["user"] != null) ? PostListResponseDataPostListDataUser.fromJson(json["user"]) : null;
    postUserCount = (json["post_user_count"] != null) ? PostListResponseDataPostListDataPostUserCount.fromJson(json["post_user_count"]) : null;
    postCount = (json["post_count"] != null) ? PostListResponseDataPostListDataPostCount.fromJson(json["post_count"]) : null;
    sharePost = (json["share_post"] != null) ? PostListResponseDataPostListDataSharePost.fromJson(json["share_post"]) : null;
    group = (json["group"] != null) ? PostListResponseDataPostListDataGroup.fromJson(json["group"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["id"] = id;
    data["user_id"] = userId;
    data["group_id"] = groupId;
    data["share_id"] = shareId;
    data["content"] = content;
    data["url"] = url;
    data["status"] = status;
    data["created_at"] = createdAt;
    data["updated_at"] = updatedAt;
    data["deleted_at"] = deletedAt;

    if (postImage != null) {
    final v = postImage;
    final arr0 = [];
    v!.forEach((v) {
    arr0.add(v!.toJson());
    });
    data["post_image"] = arr0;
    }
    if (user != null) {
    data["user"] = user!.toJson();
    }
    if (postUserCount != null) {
    data["post_user_count"] = postUserCount!.toJson();
    }
    if (postCount != null) {
    data["post_count"] = postCount!.toJson();
    }
    if (sharePost != null) {
    data["share_post"] = sharePost!.toJson();
    }
    if (group != null) {
    data["group"] = group!.toJson();
    }
    return data;
  }
}

class PostListResponseDataPostList {
/*
{
  "current_page": 1,
  "data": [
    {
      "id": 130,
      "user_id": 4,
      "group_id": 15,
      "share_id": 1,
      "content": "sample post",
      "url": null,
      "status": true,
      "created_at": "2021-09-27T09:54:36.000000Z",
      "updated_at": "2021-09-27T09:54:36.000000Z",
      "deleted_at": null,
      "post_video": [
        null
      ],
      "post_image": [
        {
          "id": 61,
          "post_id": 130,
          "url": "user/post/image/IMG_20210927_152100.jpg",
          "status": true,
          "created_at": "2021-09-27T09:54:36.000000Z",
          "updated_at": "2021-09-27T09:54:36.000000Z",
          "deleted_at": null
        }
      ],
      "user": {
        "id": 4,
        "name": "jayesh",
        "email": "jayesh@test.com",
        "mobile_number": "7304610113",
        "image": "user/profile/image/MyEmoji_20210617_224544_3896.gif"
      },
      "post_user_count": {
        "id": 53,
        "user_id": 4,
        "post_id": 130,
        "like": 1,
        "favoirate": 0,
        "created_at": "2021-09-27T09:55:17.000000Z",
        "updated_at": "2021-09-27T09:55:17.000000Z",
        "deleted_at": null
      },
      "post_count": {
        "id": 78,
        "post_id": 130,
        "like": 1,
        "favoirate": 0,
        "comment": 1,
        "share": 0,
        "created_at": "2021-09-27T09:55:17.000000Z",
        "updated_at": "2021-09-27T09:55:26.000000Z",
        "deleted_at": null
      },
      "share_post": {
        "id": 32,
        "share_by": {
          "id": 4,
          "image": "user/profile/image/MyEmoji_20210617_224544_3896.gif",
          "name": "jayesh",
          "email": "jayesh@test.com",
          "gender": "male",
          "mobile_number": "7304610113",
          "email_verified_at": null,
          "type": "customer",
          "status": true,
          "created_at": "2021-09-24T06:21:52.000000Z",
          "updated_at": "2021-09-27T09:02:25.000000Z",
          "deleted_at": null,
          "device_key": "eVveLzCaQvOLtD_UK3PIFs:APA91bEFL0m0LuQnHtbYWS6yhO656G_GJFMbiwwFHuK9iFIuRx6ZiYXATj8bN8PPq2mLfKrAimm0GSLlsayi9CNy9-n7HSDk7R8SWnSMz8d8tGdSTigHGmuyBHxUDlTb30nLdIK1SDnI",
          "device_token": null
        },
        "share_to": 4,
        "post_id": 130,
        "name": "test ooist",
        "status": true,
        "created_at": "2021-09-27T09:55:05.000000Z",
        "updated_at": "2021-09-27T09:55:05.000000Z",
        "deleted_at": null
      },
      "group": {
        "id": 15,
        "name": "new group by Grishma"
      }
    }
  ],
  "first_page_url": "https://admin.vanam.app/public/api/user-post?page=1",
  "from": 1,
  "last_page": 1,
  "last_page_url": "https://admin.vanam.app/public/api/user-post?page=1",
  "links": [
    {
      "url": null,
      "label": "&laquo; Previous",
      "active": false
    }
  ],
  "next_page_url": null,
  "path": "https://admin.vanam.app/public/api/user-post",
  "per_page": 10,
  "prev_page_url": null,
  "to": 5,
  "total": 5
}
*/

  int? currentPage;
  List<PostListResponseDataPostListData?>? data;
  String? firstPageUrl;
  int? from;
  int? lastPage;
  String? lastPageUrl;
  List<PostListResponseDataPostListLinks?>? links;
  String? nextPageUrl;
  String? path;
  int? perPage;
  String? prevPageUrl;
  int? to;
  int? total;

  PostListResponseDataPostList({
    this.currentPage,
    this.data,
    this.firstPageUrl,
    this.from,
    this.lastPage,
    this.lastPageUrl,
    this.links,
    this.nextPageUrl,
    this.path,
    this.perPage,
    this.prevPageUrl,
    this.to,
    this.total,
  });
  PostListResponseDataPostList.fromJson(Map<String, dynamic> json) {
    currentPage = json["current_page"]?.toInt();
    if (json["data"] != null) {
      final v = json["data"];
      final arr0 = <PostListResponseDataPostListData>[];
      v.forEach((v) {
        arr0.add(PostListResponseDataPostListData.fromJson(v));
      });
      this.data = arr0;
    }
    firstPageUrl = json["first_page_url"]?.toString();
    from = json["from"]?.toInt();
    lastPage = json["last_page"]?.toInt();
    lastPageUrl = json["last_page_url"]?.toString();
    if (json["links"] != null) {
      final v = json["links"];
      final arr0 = <PostListResponseDataPostListLinks>[];
      v.forEach((v) {
        arr0.add(PostListResponseDataPostListLinks.fromJson(v));
      });
      links = arr0;
    }
    nextPageUrl = json["next_page_url"]?.toString();
    path = json["path"]?.toString();
    perPage = json["per_page"]?.toInt();
    prevPageUrl = json["prev_page_url"]?.toString();
    to = json["to"]?.toInt();
    total = json["total"]?.toInt();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["current_page"] = currentPage;
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["data"] = arr0;
    }
    data["first_page_url"] = firstPageUrl;
    data["from"] = from;
    data["last_page"] = lastPage;
    data["last_page_url"] = lastPageUrl;
    if (links != null) {
      final v = links;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data["links"] = arr0;
    }
    data["next_page_url"] = nextPageUrl;
    data["path"] = path;
    data["per_page"] = perPage;
    data["prev_page_url"] = prevPageUrl;
    data["to"] = to;
    data["total"] = total;
    return data;
  }
}

class PostListResponseData {
/*
{
  "post_list": {
    "current_page": 1,
    "data": [
      {
        "id": 130,
        "user_id": 4,
        "group_id": 15,
        "share_id": 1,
        "content": "sample post",
        "url": null,
        "status": true,
        "created_at": "2021-09-27T09:54:36.000000Z",
        "updated_at": "2021-09-27T09:54:36.000000Z",
        "deleted_at": null,
        "post_video": [
          null
        ],
        "post_image": [
          {
            "id": 61,
            "post_id": 130,
            "url": "user/post/image/IMG_20210927_152100.jpg",
            "status": true,
            "created_at": "2021-09-27T09:54:36.000000Z",
            "updated_at": "2021-09-27T09:54:36.000000Z",
            "deleted_at": null
          }
        ],
        "user": {
          "id": 4,
          "name": "jayesh",
          "email": "jayesh@test.com",
          "mobile_number": "7304610113",
          "image": "user/profile/image/MyEmoji_20210617_224544_3896.gif"
        },
        "post_user_count": {
          "id": 53,
          "user_id": 4,
          "post_id": 130,
          "like": 1,
          "favoirate": 0,
          "created_at": "2021-09-27T09:55:17.000000Z",
          "updated_at": "2021-09-27T09:55:17.000000Z",
          "deleted_at": null
        },
        "post_count": {
          "id": 78,
          "post_id": 130,
          "like": 1,
          "favoirate": 0,
          "comment": 1,
          "share": 0,
          "created_at": "2021-09-27T09:55:17.000000Z",
          "updated_at": "2021-09-27T09:55:26.000000Z",
          "deleted_at": null
        },
        "share_post": {
          "id": 32,
          "share_by": {
            "id": 4,
            "image": "user/profile/image/MyEmoji_20210617_224544_3896.gif",
            "name": "jayesh",
            "email": "jayesh@test.com",
            "gender": "male",
            "mobile_number": "7304610113",
            "email_verified_at": null,
            "type": "customer",
            "status": true,
            "created_at": "2021-09-24T06:21:52.000000Z",
            "updated_at": "2021-09-27T09:02:25.000000Z",
            "deleted_at": null,
            "device_key": "eVveLzCaQvOLtD_UK3PIFs:APA91bEFL0m0LuQnHtbYWS6yhO656G_GJFMbiwwFHuK9iFIuRx6ZiYXATj8bN8PPq2mLfKrAimm0GSLlsayi9CNy9-n7HSDk7R8SWnSMz8d8tGdSTigHGmuyBHxUDlTb30nLdIK1SDnI",
            "device_token": null
          },
          "share_to": 4,
          "post_id": 130,
          "name": "test ooist",
          "status": true,
          "created_at": "2021-09-27T09:55:05.000000Z",
          "updated_at": "2021-09-27T09:55:05.000000Z",
          "deleted_at": null
        },
        "group": {
          "id": 15,
          "name": "new group by Grishma"
        }
      }
    ],
    "first_page_url": "https://admin.vanam.app/public/api/user-post?page=1",
    "from": 1,
    "last_page": 1,
    "last_page_url": "https://admin.vanam.app/public/api/user-post?page=1",
    "links": [
      {
        "url": null,
        "label": "&laquo; Previous",
        "active": false
      }
    ],
    "next_page_url": null,
    "path": "https://admin.vanam.app/public/api/user-post",
    "per_page": 10,
    "prev_page_url": null,
    "to": 5,
    "total": 5
  }
}
*/

  PostListResponseDataPostList? postList;

  PostListResponseData({
    this.postList,
  });
  PostListResponseData.fromJson(Map<String, dynamic> json) {
    postList = (json["post_list"] != null) ? PostListResponseDataPostList.fromJson(json["post_list"]) : null;
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    if (postList != null) {
      data["post_list"] = postList!.toJson();
    }
    return data;
  }
}

class PostListResponse {
/*
{
  "success": true,
  "data": {
    "post_list": {
      "current_page": 1,
      "data": [
        {
          "id": 130,
          "user_id": 4,
          "group_id": 15,
          "share_id": 1,
          "content": "sample post",
          "url": null,
          "status": true,
          "created_at": "2021-09-27T09:54:36.000000Z",
          "updated_at": "2021-09-27T09:54:36.000000Z",
          "deleted_at": null,
          "post_video": [
            null
          ],
          "post_image": [
            {
              "id": 61,
              "post_id": 130,
              "url": "user/post/image/IMG_20210927_152100.jpg",
              "status": true,
              "created_at": "2021-09-27T09:54:36.000000Z",
              "updated_at": "2021-09-27T09:54:36.000000Z",
              "deleted_at": null
            }
          ],
          "user": {
            "id": 4,
            "name": "jayesh",
            "email": "jayesh@test.com",
            "mobile_number": "7304610113",
            "image": "user/profile/image/MyEmoji_20210617_224544_3896.gif"
          },
          "post_user_count": {
            "id": 53,
            "user_id": 4,
            "post_id": 130,
            "like": 1,
            "favoirate": 0,
            "created_at": "2021-09-27T09:55:17.000000Z",
            "updated_at": "2021-09-27T09:55:17.000000Z",
            "deleted_at": null
          },
          "post_count": {
            "id": 78,
            "post_id": 130,
            "like": 1,
            "favoirate": 0,
            "comment": 1,
            "share": 0,
            "created_at": "2021-09-27T09:55:17.000000Z",
            "updated_at": "2021-09-27T09:55:26.000000Z",
            "deleted_at": null
          },
          "share_post": {
            "id": 32,
            "share_by": {
              "id": 4,
              "image": "user/profile/image/MyEmoji_20210617_224544_3896.gif",
              "name": "jayesh",
              "email": "jayesh@test.com",
              "gender": "male",
              "mobile_number": "7304610113",
              "email_verified_at": null,
              "type": "customer",
              "status": true,
              "created_at": "2021-09-24T06:21:52.000000Z",
              "updated_at": "2021-09-27T09:02:25.000000Z",
              "deleted_at": null,
              "device_key": "eVveLzCaQvOLtD_UK3PIFs:APA91bEFL0m0LuQnHtbYWS6yhO656G_GJFMbiwwFHuK9iFIuRx6ZiYXATj8bN8PPq2mLfKrAimm0GSLlsayi9CNy9-n7HSDk7R8SWnSMz8d8tGdSTigHGmuyBHxUDlTb30nLdIK1SDnI",
              "device_token": null
            },
            "share_to": 4,
            "post_id": 130,
            "name": "test ooist",
            "status": true,
            "created_at": "2021-09-27T09:55:05.000000Z",
            "updated_at": "2021-09-27T09:55:05.000000Z",
            "deleted_at": null
          },
          "group": {
            "id": 15,
            "name": "new group by Grishma"
          }
        }
      ],
      "first_page_url": "https://admin.vanam.app/public/api/user-post?page=1",
      "from": 1,
      "last_page": 1,
      "last_page_url": "https://admin.vanam.app/public/api/user-post?page=1",
      "links": [
        {
          "url": null,
          "label": "&laquo; Previous",
          "active": false
        }
      ],
      "next_page_url": null,
      "path": "https://admin.vanam.app/public/api/user-post",
      "per_page": 10,
      "prev_page_url": null,
      "to": 5,
      "total": 5
    }
  },
  "message": "Post   list."
}
*/

  bool? success;
  PostListResponseData? data;
  String? message;

  PostListResponse({
    this.success,
    this.data,
    this.message,
  });
  PostListResponse.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    data = (json["data"] != null) ? PostListResponseData.fromJson(json["data"]) : null;
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["message"] = message;
    return data;
  }
}
