///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class PostDeleteResponseData {
/*
{
  "post": "successfully"
}
*/

  String? post;

  PostDeleteResponseData({
    this.post,
  });
  PostDeleteResponseData.fromJson(Map<String, dynamic> json) {
    post = json["post"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["post"] = post;
    return data;
  }
}

class PostDeleteResponse {
/*
{
  "success": true,
  "data": {
    "post": "successfully"
  },
  "message": "Delete successfully."
}
*/

  bool? success;
  PostDeleteResponseData? data;
  String? message;

  PostDeleteResponse({
    this.success,
    this.data,
    this.message,
  });
  PostDeleteResponse.fromJson(Map<String, dynamic> json) {
    success = json["success"];
    data = (json["data"] != null) ? PostDeleteResponseData.fromJson(json["data"]) : null;
    message = json["message"]?.toString();
  }
  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = Map<String, dynamic>();
    data["success"] = success;
    if (data != null) {
      data["data"] = this.data!.toJson();
    }
    data["message"] = message;
    return data;
  }
}
